.nh
.TH "X86-VRSQRT28SD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
VRSQRT28SD - APPROXIMATION TO THE RECIPROCAL SQUARE ROOT OF SCALAR DOUBLE-PRECISION FLOATING-POINT VALUE WITH LESS THAN 2^-28 RELATIVE ERROR
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
EVEX.LIG.66.0F38.W1 CD /r VRSQRT28SD xmm1 {k1}{z}, xmm2, xmm3/m64 {sae}
T}
	A	V/V	AVX512ER	T{
Computes approximate reciprocal square root (
T}
\&lt;
T{
2^\-28 relative error) of the scalar double\-precision floating\-point value from xmm3/m64 and stores result in xmm1with writemask k1. Also, upper double\-precision floating\-point value (bits
T}
[
127:64
]
) from xmm2 is copied to xmm1
[
127:64
]
\&.
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	Tuple1 Scalar	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SS Description
.PP
Computes the reciprocal square root of the low float64 value in the
second source operand (the third operand) and store the result to the
destination operand (the first operand). The approximate reciprocal
square root is evaluated with less than 2^\-28 of maximum relative error.
The result is written into the low float64 element of xmm1 according to
the writemask k1. Bits 127:64 of the destination is copied from the
corresponding bits of the first source operand (the second operand).

.PP
If any source element is NaN, the quietized NaN source value is returned
for that element. Negative (non\-zero) source numbers, as well as \-∞,
return the canonical NaN and set the Invalid Flag (#I).

.PP
A value of \-0 must return \-∞ and set the DivByZero flags (#Z). Negative
numbers should return NaN and set the Invalid flag (#I). Note however
that the instruction flush input denormals to zero of the same sign, so
negative denormals return \-∞ and set the DivByZero flag.

.PP
The first source operand is an XMM register. The second source operand
is an XMM register or a 64\-bit memory location. The destination operand
is a XMM register.

.SS A numerically exact implementation of VRSQRT28xx can be found at https://software.intel.com/en\-us/arti\-
.SS cles/reference\-implementations\-for\-IA\-approximation\-instructions\-vrcp14\-vrsqrt14\-vrcp28\-vrsqrt28\-vexp2.
.SS Operation
.SS VRSQRT28SD (EVEX encoded versions)
.PP
.RS

.nf
    IF k1[0] OR *no writemask* THEN
                DEST[63: 0]←(1.0/ SQRT(SRC[63: 0]));
    ELSE
        IF *merging\-masking* ; merging\-masking
            THEN *DEST[63: 0] remains unchanged*
            ELSE ; zeroing\-masking
                    DEST[63: 0]←0
        FI;
    FI;
ENDFOR;
DEST[127:64]←SRC1[127: 64]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.TS
allbox;
l l l 
l l l .
\fB\fCInput value\fR	\fB\fCResult value\fR	\fB\fCComments\fR
NAN	QNAN(input)	If (SRC = SNaN) then 
#
I
X = 2\-2n	2n	X\&lt;0	QNaN\_Indefinite	Including \-INF
X = \-0 or negative denormal	\-INF	
#
Z
X = +0 or positive denormal	+INF	
#
Z
X = +INF	+0	.TE

.PP
Table 6\-40. VRSQRT28SD Special Cases

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VRSQRT28SD \_\_m128d \_mm\_rsqrt28\_round\_sd(\_\_m128d a, \_\_m128d b, int rounding);

VRSQRT28SD \_\_m128d \_mm\_mask\_rsqrt28\_round\_sd(\_\_m128d s, \_\_mmask8 m,\_\_m128d a, \_\_m128d b, int rounding);

VRSQRT28SD \_\_m128d \_mm\_maskz\_rsqrt28\_round\_sd( \_\_mmask8 m,\_\_m128d a, \_\_m128d b, int rounding);

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
Invalid (if SNaN input), Divide\-by\-zero

.SS Other Exceptions
.PP
See Exceptions Type E3.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
