.nh
.TH "X86-ORPS" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
ORPS - BITWISE LOGICAL OR OF PACKED SINGLE PRECISION FLOATING-POINT VALUES
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp / En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
NP 0F 56 /r ORPS xmm1, xmm2/m128
T}
	A	V/V	SSE	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in xmm1 and xmm2/mem.
T}
T{
VEX.128.0F 56 /r VORPS xmm1,xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in xmm2 and xmm3/mem.
T}
T{
VEX.256.0F 56 /r VORPS ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in ymm2 and ymm3/mem.
T}
T{
EVEX.128.0F.W0 56 /r VORPS xmm1 {k1}{z}, xmm2, xmm3/m128/m32bcst
T}
	C	V/V	AVX512VL AVX512DQ	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in xmm2 and xmm3/m128/m32bcst subject to writemask k1.
T}
T{
EVEX.256.0F.W0 56 /r VORPS ymm1 {k1}{z}, ymm2, ymm3/m256/m32bcst
T}
	C	V/V	AVX512VL AVX512DQ	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in ymm2 and ymm3/m256/m32bcst subject to writemask k1.
T}
T{
EVEX.512.0F.W0 56 /r VORPS zmm1 {k1}{z}, zmm2, zmm3/m512/m32bcst
T}
	C	V/V	AVX512DQ	T{
Return the bitwise logical OR of packed single\-precision floating\-point values in zmm2 and zmm3/m512/m32bcst subject to writemask k1.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
B	NA	ModRM:reg (w)	VEX.vvvv (r)	ModRM:r/m (r)	NA
C	Full	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SS Description
.PP
Performs a bitwise logical OR of the four, eight or sixteen packed
single\-precision floating\-point values from the first source operand and
the second source operand, and stores the result in the destination
operand

.PP
EVEX encoded versions: The first source operand is a ZMM/YMM/XMM
register. The second source operand can be a ZMM/YMM/XMM register, a
512/256/128\-bit memory location, or a 512/256/128\-bit vector broadcasted
from a 32\-bit memory location. The destination operand is a ZMM/YMM/XMM
register conditionally updated with writemask k1.

.PP
VEX.256 encoded version: The first source operand is a YMM register. The
second source operand is a YMM register or a 256\-bit memory location.
The destination operand is a YMM register. The upper bits (MAXVL\-1:256)
of the corresponding ZMM register destination are zeroed.

.PP
VEX.128 encoded version: The first source operand is an XMM register.
The second source operand is an XMM register or 128\-bit memory location.
The destination operand is an XMM register. The upper bits (MAXVL\-1:128)
of the corresponding ZMM register destination are zeroed.

.PP
128\-bit Legacy SSE version: The second source can be an XMM register or
an 128\-bit memory location. The destination is not distinct from the
first source XMM register and the upper bits (MAXVL\-1:128) of the
corresponding register destination are unmodified.

.SS Operation
.SS VORPS (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (4, 128), (8, 256), (16, 512)
FOR j←0 TO KL\-1
    i←j * 32
    IF k1[j] OR *no writemask*
        THEN
            IF (EVEX.b == 1) AND (SRC2 *is memory*)
                THEN
                    DEST[i+31:i]←SRC1[i+31:i] BITWISE OR SRC2[31:0]
                ELSE
                    DEST[i+31:i]←SRC1[i+31:i] BITWISE OR SRC2[i+31:i]
            FI;
        ELSE
            IF *merging\-masking* ; merging\-masking
                THEN *DEST[i+31:i] remains unchanged*
                ELSE *zeroing\-masking*
                        ; zeroing\-masking
                    DEST[i+31:i] ← 0
            FI
    FI;
ENDFOR
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VORPS (VEX.256 encoded version)
.PP
.RS

.nf
DEST[31:0]←SRC1[31:0] BITWISE OR SRC2[31:0]
DEST[63:32]←SRC1[63:32] BITWISE OR SRC2[63:32]
DEST[95:64]←SRC1[95:64] BITWISE OR SRC2[95:64]
DEST[127:96]←SRC1[127:96] BITWISE OR SRC2[127:96]
DEST[159:128]←SRC1[159:128] BITWISE OR SRC2[159:128]
DEST[191:160]←SRC1[191:160] BITWISE OR SRC2[191:160]
DEST[223:192]←SRC1[223:192] BITWISE OR SRC2[223:192]
DEST[255:224]←SRC1[255:224] BITWISE OR SRC2[255:224].
DEST[MAXVL\-1:256] ← 0

.fi
.RE

.SS VORPS (VEX.128 encoded version)
.PP
.RS

.nf
DEST[31:0]←SRC1[31:0] BITWISE OR SRC2[31:0]
DEST[63:32]←SRC1[63:32] BITWISE OR SRC2[63:32]
DEST[95:64]←SRC1[95:64] BITWISE OR SRC2[95:64]
DEST[127:96]←SRC1[127:96] BITWISE OR SRC2[127:96]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS ORPS (128\-bit Legacy SSE version)
.PP
.RS

.nf
DEST[31:0]←SRC1[31:0] BITWISE OR SRC2[31:0]
DEST[63:32]←SRC1[63:32] BITWISE OR SRC2[63:32]
DEST[95:64]←SRC1[95:64] BITWISE OR SRC2[95:64]
DEST[127:96]←SRC1[127:96] BITWISE OR SRC2[127:96]
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VORPS \_\_m512 \_mm512\_or\_ps ( \_\_m512 a, \_\_m512 b);

VORPS \_\_m512 \_mm512\_mask\_or\_ps ( \_\_m512 s, \_\_mmask16 k, \_\_m512 a, \_\_m512 b);

VORPS \_\_m512 \_mm512\_maskz\_or\_ps (\_\_mmask16 k, \_\_m512 a, \_\_m512 b);

VORPS \_\_m256 \_mm256\_mask\_or\_ps (\_\_m256 s, \_\_\_mmask8 k, \_\_m256 a, \_\_m256 b);

VORPS \_\_m256 \_mm256\_maskz\_or\_ps (\_\_mmask8 k, \_\_m256 a, \_\_m256 b);

VORPS \_\_m128 \_mm\_mask\_or\_ps ( \_\_m128 s, \_\_mmask8 k, \_\_m128 a, \_\_m128 b);

VORPS \_\_m128 \_mm\_maskz\_or\_ps (\_\_mmask8 k, \_\_m128 a, \_\_m128 b);

VORPS \_\_m256 \_mm256\_or\_ps (\_\_m256 a, \_\_m256 b);

ORPS \_\_m128 \_mm\_or\_ps (\_\_m128 a, \_\_m128 b);

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
None

.SS Other Exceptions
.PP
Non\-EVEX\-encoded instruction, see Exceptions Type 4.

.PP
EVEX\-encoded instruction, see Exceptions Type E4.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
