.nh
.TH "X86-SUBPD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
SUBPD - SUBTRACT PACKED DOUBLE-PRECISION FLOATING-POINT VALUES
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
66 0F 5C /r SUBPD xmm1, xmm2/m128
T}
	A	V/V	SSE2	T{
Subtract packed double\-precision floating\-point values in xmm2/mem from xmm1 and store result in xmm1.
T}
T{
VEX.128.66.0F.WIG 5C /r VSUBPD xmm1,xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Subtract packed double\-precision floating\-point values in xmm3/mem from xmm2 and store result in xmm1.
T}
T{
VEX.256.66.0F.WIG 5C /r VSUBPD ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX	T{
Subtract packed double\-precision floating\-point values in ymm3/mem from ymm2 and store result in ymm1.
T}
T{
EVEX.128.66.0F.W1 5C /r VSUBPD xmm1 {k1}{z}, xmm2, xmm3/m128/m64bcst
T}
	C	V/V	AVX512VL AVX512F	T{
Subtract packed double\-precision floating\-point values from xmm3/m128/m64bcst to xmm2 and store result in xmm1 with writemask k1.
T}
T{
EVEX.256.66.0F.W1 5C /r VSUBPD ymm1 {k1}{z}, ymm2, ymm3/m256/m64bcst
T}
	C	V/V	AVX512VL AVX512F	T{
Subtract packed double\-precision floating\-point values from ymm3/m256/m64bcst to ymm2 and store result in ymm1 with writemask k1.
T}
T{
EVEX.512.66.0F.W1 5C /r VSUBPD zmm1 {k1}{z}, zmm2, zmm3/m512/m64bcst{er}
T}
	C	V/V	AVX512F	T{
Subtract packed double\-precision floating\-point values from zmm3/m512/m64bcst to zmm2 and store result in zmm1 with writemask k1.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
B	NA	ModRM:reg (w)	VEX.vvvv (r)	ModRM:r/m (r)	NA
C	Full	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SS Description
.PP
Performs a SIMD subtract of the two, four or eight packed
double\-precision floating\-point values of the second Source operand from
the first Source operand, and stores the packed double\-precision
floating\-point results in the destination operand.

.PP
VEX.128 and EVEX.128 encoded versions: The second source operand is an
XMM register or an 128\-bit memory location. The first source operand and
destination operands are XMM registers. Bits (MAXVL\-1:128) of the
corresponding destination register are zeroed.

.PP
VEX.256 and EVEX.256 encoded versions: The second source operand is an
YMM register or an 256\-bit memory location. The first source operand and
destination operands are YMM registers. Bits (MAXVL\-1:256) of the
corresponding destination register are zeroed.

.PP
EVEX.512 encoded version: The second source operand is a ZMM register, a
512\-bit memory location or a 512\-bit vector broadcasted from a 64\-bit
memory location. The first source operand and destination operands are
ZMM registers. The destination operand is conditionally updated
according to the writemask.

.PP
128\-bit Legacy SSE version: The second source can be an XMM register or
an 128\-bit memory location. The destination is not distinct from the
first source XMM register and the upper Bits (MAXVL\-1:128) of the
corresponding register destination are unmodified.

.SS Operation
.SS VSUBPD (EVEX encoded versions) when src2 operand is a vector register
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
IF (VL = 512) AND (EVEX.b = 1)
    THEN
        SET\_RM(EVEX.RC);
    ELSE
        SET\_RM(MXCSR.RM);
FI;
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask*
        THEN DEST[i+63:i]←SRC1[i+63:i] \- SRC2[i+63:i]
    ELSE
        IF *merging\-masking* ; merging\-masking
            THEN *DEST[63:0] remains unchanged*
            ELSE ; zeroing\-masking
                DEST[63:0] ← 0
        FI;
    FI;
ENDFOR
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VSUBPD (EVEX encoded versions) when src2 operand is a memory source
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask* THEN
            IF (EVEX.b = 1)
                THEN DEST[i+63:i]←SRC1[i+63:i] \- SRC2[63:0];
                ELSE EST[i+63:i]←SRC1[i+63:i] \- SRC2[i+63:i];
            FI;
    ELSE
        IF *merging\-masking* ; merging\-masking
            THEN *DEST[63:0] remains unchanged*
            ELSE ; zeroing\-masking
                DEST[63:0] ← 0
        FI;
    FI;
ENDFOR
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VSUBPD (VEX.256 encoded version)
.PP
.RS

.nf
DEST[63:0]←SRC1[63:0] \- SRC2[63:0]
DEST[127:64]←SRC1[127:64] \- SRC2[127:64]
DEST[191:128]←SRC1[191:128] \- SRC2[191:128]
DEST[255:192]←SRC1[255:192] \- SRC2[255:192]
DEST[MAXVL\-1:256] ← 0

.fi
.RE

.SS VSUBPD (VEX.128 encoded version)
.PP
.RS

.nf
DEST[63:0]←SRC1[63:0] \- SRC2[63:0]
DEST[127:64]←SRC1[127:64] \- SRC2[127:64]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS SUBPD (128\-bit Legacy SSE version)
.PP
.RS

.nf
DEST[63:0]←DEST[63:0] \- SRC[63:0]
DEST[127:64]←DEST[127:64] \- SRC[127:64]
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VSUBPD \_\_m512d \_mm512\_sub\_pd (\_\_m512d a, \_\_m512d b);

VSUBPD \_\_m512d \_mm512\_mask\_sub\_pd (\_\_m512d s, \_\_mmask8 k, \_\_m512d a, \_\_m512d b);

VSUBPD \_\_m512d \_mm512\_maskz\_sub\_pd (\_\_mmask8 k, \_\_m512d a, \_\_m512d b);

VSUBPD \_\_m512d \_mm512\_sub\_round\_pd (\_\_m512d a, \_\_m512d b, int);

VSUBPD \_\_m512d \_mm512\_mask\_sub\_round\_pd (\_\_m512d s, \_\_mmask8 k, \_\_m512d a, \_\_m512d b, int);

VSUBPD \_\_m512d \_mm512\_maskz\_sub\_round\_pd (\_\_mmask8 k, \_\_m512d a, \_\_m512d b, int);

VSUBPD \_\_m256d \_mm256\_sub\_pd (\_\_m256d a, \_\_m256d b);

VSUBPD \_\_m256d \_mm256\_mask\_sub\_pd (\_\_m256d s, \_\_mmask8 k, \_\_m256d a, \_\_m256d b);

VSUBPD \_\_m256d \_mm256\_maskz\_sub\_pd (\_\_mmask8 k, \_\_m256d a, \_\_m256d b);

SUBPD \_\_m128d \_mm\_sub\_pd (\_\_m128d a, \_\_m128d b);

VSUBPD \_\_m128d \_mm\_mask\_sub\_pd (\_\_m128d s, \_\_mmask8 k, \_\_m128d a, \_\_m128d b);

VSUBPD \_\_m128d \_mm\_maskz\_sub\_pd (\_\_mmask8 k, \_\_m128d a, \_\_m128d b);

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
Overflow, Underflow, Invalid, Precision, Denormal

.SS Other Exceptions
.PP
VEX\-encoded instructions, see Exceptions Type 2.

.PP
EVEX\-encoded instructions, see Exceptions Type E2.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
