.nh
.TH "X86-LDS-LES-LFS-LGS-LSS" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
LDS-LES-LFS-LGS-LSS - LOAD FAR POINTER
.TS
allbox;
l l l l l l 
l l l l l l .
\fB\fCOpcode\fR	\fB\fCInstruction\fR	\fB\fCOp/En\fR	\fB\fC64\-Bit Mode\fR	\fB\fCCompat/Leg Mode\fR	\fB\fCDescription\fR
C5 /r	LDS r16,m16:16	RM	Invalid	Valid	T{
Load DS:r16 with far pointer from memory.
T}
C5 /r	LDS r32,m16:32	RM	Invalid	Valid	T{
Load DS:r32 with far pointer from memory.
T}
0F B2 /r	LSS r16,m16:16	RM	Valid	Valid	T{
Load SS:r16 with far pointer from memory.
T}
0F B2 /r	LSS r32,m16:32	RM	Valid	Valid	T{
Load SS:r32 with far pointer from memory.
T}
REX + 0F B2 /r	LSS r64,m16:64	RM	Valid	N.E.	T{
Load SS:r64 with far pointer from memory.
T}
C4 /r	LES r16,m16:16	RM	Invalid	Valid	T{
Load ES:r16 with far pointer from memory.
T}
C4 /r	LES r32,m16:32	RM	Invalid	Valid	T{
Load ES:r32 with far pointer from memory.
T}
0F B4 /r	LFS r16,m16:16	RM	Valid	Valid	T{
Load FS:r16 with far pointer from memory.
T}
0F B4 /r	LFS r32,m16:32	RM	Valid	Valid	T{
Load FS:r32 with far pointer from memory.
T}
REX + 0F B4 /r	LFS r64,m16:64	RM	Valid	N.E.	T{
Load FS:r64 with far pointer from memory.
T}
0F B5 /r	LGS r16,m16:16	RM	Valid	Valid	T{
Load GS:r16 with far pointer from memory.
T}
0F B5 /r	LGS r32,m16:32	RM	Valid	Valid	T{
Load GS:r32 with far pointer from memory.
T}
REX + 0F B5 /r	LGS r64,m16:64	RM	Valid	N.E.	T{
Load GS:r64 with far pointer from memory.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l 
l l l l l .
Op/En	Operand 1	Operand 2	Operand 3	Operand 4
RM	ModRM:reg (w)	ModRM:r/m (r)	NA	NA
.TE

.SH DESCRIPTION
.PP
Loads a far pointer (segment selector and offset) from the second
operand (source operand) into a segment register and the first operand
(destination operand). The source operand specifies a 48\-bit or a 32\-bit
pointer in memory depending on the current setting of the operand\-size
attribute (32 bits or 16 bits, respectively). The instruction opcode and
the destination operand specify a segment register/general\-purpose
register pair. The 16\-bit segment selector from the source operand is
loaded into the segment register specified with the opcode (DS, SS, ES,
FS, or GS). The 32\-bit or 16\-bit offset is loaded into the register
specified with the destination operand.

.PP
If one of these instructions is executed in protected mode, additional
information from the segment descriptor pointed to by the segment
selector in the source operand is loaded in the hidden part of the
selected segment register.

.PP
Also in protected mode, a NULL selector (values 0000 through 0003) can
be loaded into DS, ES, FS, or GS registers without causing a protection
exception. (Any subsequent reference to a segment whose corresponding
segment register is loaded with a NULL selector, causes a
general\-protection exception (#GP) and no memory reference to the
segment occurs.)

.PP
In 64\-bit mode, the instruction’s default operation size is 32 bits.
Using a REX prefix in the form of REX.W promotes operation to specify a
source operand referencing an 80\-bit pointer (16\-bit selector, 64\-bit
offset) in memory. Using a REX prefix in the form of REX.R permits
access to additional registers (R8\-R15). See the summary chart at the
beginning of this section for encoding data and limits.

.SH OPERATION
.PP
.RS

.nf
64\-BIT\_MODE
    IF SS is loaded
        THEN
            IF SegmentSelector = NULL and ( (RPL = 3) or
                    (RPL ≠ 3 and RPL ≠ CPL) )
                THEN #GP(0);
            ELSE IF descriptor is in non\-canonical space
                THEN #GP(0); FI;
            ELSE IF Segment selector index is not within descriptor table limits
                    or segment selector RPL ≠ CPL
                    or access rights indicate nonwritable data segment
                    or DPL ≠ CPL
                THEN #GP(selector); FI;
            ELSE IF Segment marked not present
                THEN #SS(selector); FI;
            FI;
            SS ← SegmentSelector(SRC);
            SS ← SegmentDescriptor([SRC]);
    ELSE IF attempt to load DS, or ES
        THEN #UD;
    ELSE IF FS, or GS is loaded with non\-NULL segment selector
        THEN IF Segment selector index is not within descriptor table limits
            or access rights indicate segment neither data nor readable code segment
            or segment is data or nonconforming\-code segment
            and ( RPL > DPL or CPL > DPL)
                THEN #GP(selector); FI;
            ELSE IF Segment marked not present
                THEN #NP(selector); FI;
            FI;
            SegmentRegister ← SegmentSelector(SRC) ;
            SegmentRegister ← SegmentDescriptor([SRC]);
        FI;
    ELSE IF FS, or GS is loaded with a NULL selector:
        THEN
            SegmentRegister ← NULLSelector;
            SegmentRegister(DescriptorValidBit) ← 0; FI; (* Hidden flag;
                not accessible by software *)
    FI;
    DEST ← Offset(SRC);
PREOTECTED MODE OR COMPATIBILITY MODE;
    IF SS is loaded
        THEN
            IF SegementSelector = NULL
                THEN #GP(0);
            ELSE IF Segment selector index is not within descriptor table limits
                    or segment selector RPL ≠ CPL
                    or access rights indicate nonwritable data segment
                    or DPL ≠ CPL
                THEN #GP(selector); FI;
            ELSE IF Segment marked not present
                THEN #SS(selector); FI;
            FI;
            SS ← SegmentSelector(SRC);
            SS ← SegmentDescriptor([SRC]);
    ELSE IF DS, ES, FS, or GS is loaded with non\-NULL segment selector
        THEN IF Segment selector index is not within descriptor table limits
            or access rights indicate segment neither data nor readable code segment
            or segment is data or nonconforming\-code segment
            and (RPL > DPL or CPL > DPL)
                THEN #GP(selector); FI;
            ELSE IF Segment marked not present
                THEN #NP(selector); FI;
            FI;
            SegmentRegister ← SegmentSelector(SRC) AND RPL;
            SegmentRegister ← SegmentDescriptor([SRC]);
        FI;
    ELSE IF DS, ES, FS, or GS is loaded with a NULL selector:
        THEN
            SegmentRegister ← NULLSelector;
            SegmentRegister(DescriptorValidBit) ← 0; FI; (* Hidden flag;
                not accessible by software *)
    FI;
    DEST ← Offset(SRC);
Real\-Address or Virtual\-8086 Mode
    SegmentRegister ← SegmentSelector(SRC); FI;
    DEST ← Offset(SRC);

.fi
.RE

.SH FLAGS AFFECTED
.PP
None

.SH PROTECTED MODE EXCEPTIONS
.TS
allbox;
l l 
l l .
#UD	T{
If source operand is not a memory location.
T}
	If the LOCK prefix is used.
#GP(0)	T{
If a NULL selector is loaded into the SS register.
T}
	T{
If a memory operand effective address is outside the CS, DS, ES, FS, or GS segment limit.
T}
	T{
If the DS, ES, FS, or GS register is used to access memory and it contains a NULL segment selector.
T}
#GP(selector)	T{
If the SS register is being loaded and any of the following is true: the segment selector index is not within the descriptor table limits, the segment selector RPL is not equal to CPL, the segment is a non\-writable data segment, or DPL is not equal to CPL.
T}
	T{
If the DS, ES, FS, or GS register is being loaded with a non\-NULL segment selector and any of the following is true: the segment selector index is not within descriptor table limits, the segment is neither a data nor a readable code segment, or the segment is a data or nonconforming\-code segment and both RPL and CPL are greater than DPL.
T}
#SS(0)	T{
If a memory operand effective address is outside the SS segment limit.
T}
#SS(selector)	T{
If the SS register is being loaded and the segment is marked not present.
T}
#NP(selector)	T{
If DS, ES, FS, or GS register is being loaded with a non\-NULL segment selector and the segment is marked not present.
T}
#PF(fault\-code)	If a page fault occurs.
#AC(0)	T{
If alignment checking is enabled and an unaligned memory reference is made while the current privilege level is 3.
T}
.TE

.SH REAL\-ADDRESS MODE EXCEPTIONS
.TS
allbox;
l l 
l l .
#GP	T{
If a memory operand effective address is outside the CS, DS, ES, FS, or GS segment limit.
T}
#SS	T{
If a memory operand effective address is outside the SS segment limit.
T}
#UD	T{
If source operand is not a memory location.
T}
	If the LOCK prefix is used.
.TE

.SH VIRTUAL\-8086 MODE EXCEPTIONS
.TS
allbox;
l l 
l l .
#UD	T{
If source operand is not a memory location.
T}
	If the LOCK prefix is used.
#GP(0)	T{
If a memory operand effective address is outside the CS, DS, ES, FS, or GS segment limit.
T}
#SS(0)	T{
If a memory operand effective address is outside the SS segment limit.
T}
#PF(fault\-code)	If a page fault occurs.
#AC(0)	T{
If alignment checking is enabled and an unaligned memory reference is made.
T}
.TE

.SH COMPATIBILITY MODE EXCEPTIONS
.PP
Same exceptions as in protected mode.

.SH 64\-BIT MODE EXCEPTIONS
.TS
allbox;
l l 
l l .
#GP(0)	T{
If the memory address is in a non\-canonical form.
T}
	T{
If a NULL selector is attempted to be loaded into the SS register in compatibility mode.
T}
	T{
If a NULL selector is attempted to be loaded into the SS register in CPL3 and 64\-bit mode.
T}
	T{
If a NULL selector is attempted to be loaded into the SS register in non\-CPL3 and 64\-bit mode where its RPL is not equal to CPL.
T}
#GP(Selector)	T{
If the FS, or GS register is being loaded with a non\-NULL segment selector and any of the following is true: the segment selector index is not within descriptor table limits, the memory address of the descriptor is non\-canonical, the segment is neither a data nor a readable code segment, or the segment is a data or nonconforming\-code segment and both RPL and CPL are greater than DPL.
T}
	T{
If the SS register is being loaded and any of the following is true: the segment selector index is not within the descriptor table limits, the memory address of the descriptor is non\-canonical, the segment selector RPL is not equal to CPL, the segment is a nonwritable data segment, or DPL is not equal to CPL.
T}
#SS(0)	T{
If a memory operand effective address is non\-canonical
T}
#SS(Selector)	T{
If the SS register is being loaded and the segment is marked not present.
T}
#NP(selector)	T{
If FS, or GS register is being loaded with a non\-NULL segment selector and the segment is marked not present.
T}
#PF(fault\-code)	If a page fault occurs.
#AC(0)	T{
If alignment checking is enabled and an unaligned memory reference is made while the current privilege level is 3.
T}
#UD	T{
If source operand is not a memory location.
T}
	If the LOCK prefix is used.
.TE

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
