.nh
.TH "X86-PMAXSB-PMAXSW-PMAXSD-PMAXSQ" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
PMAXSB-PMAXSW-PMAXSD-PMAXSQ - MAXIMUM OF PACKED SIGNED INTEGERS
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp / En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
NP 0F EE /mm1, mm2/m64	A	V/V	SSE	T{
Compare signed word integers in mm1 and return maximum values.
T}
T{
66 0F 38 3C /r PMAXSB xmm1, xmm2/m128
T}
	A	V/V	SSE4\_1	T{
Compare packed signed byte integers in xmm1 and xmm2/m128 and store packed maximum values in xmm1.
T}
T{
66 0F EE /r PMAXSW xmm1, xmm2/m128
T}
	A	V/V	SSE2	T{
Compare packed signed word integers in xmm2/m128 and xmm1 and stores maximum packed values in xmm1.
T}
T{
66 0F 38 3D /r PMAXSD xmm1, xmm2/m128
T}
	A	V/V	SSE4\_1	T{
Compare packed signed dword integers in xmm1 and xmm2/m128 and store packed maximum values in xmm1.
T}
T{
VEX.128.66.0F38.WIG 3C /r VPMAXSB xmm1, xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Compare packed signed byte integers in xmm2 and xmm3/m128 and store packed maximum values in xmm1.
T}
T{
VEX.128.66.0F.WIG EE /r VPMAXSW xmm1, xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Compare packed signed word integers in xmm3/m128 and xmm2 and store packed maximum values in xmm1.
T}
T{
VEX.128.66.0F38.WIG 3D /r VPMAXSD xmm1, xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Compare packed signed dword integers in xmm2 and xmm3/m128 and store packed maximum values in xmm1.
T}
T{
VEX.256.66.0F38.WIG 3C /r VPMAXSB ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX2	T{
Compare packed signed byte integers in ymm2 and ymm3/m256 and store packed maximum values in ymm1.
T}
T{
VEX.256.66.0F.WIG EE /r VPMAXSW ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX2	T{
Compare packed signed word integers in ymm3/m256 and ymm2 and store packed maximum values in ymm1.
T}
T{
VEX.256.66.0F38.WIG 3D /r VPMAXSD ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX2	T{
Compare packed signed dword integers in ymm2 and ymm3/m256 and store packed maximum values in ymm1.
T}
T{
EVEX.128.66.0F38.WIG 3C /r VPMAXSB xmm1{k1}{z}, xmm2, xmm3/m128
T}
	C	V/V	AVX512VL AVX512BW	T{
Compare packed signed byte integers in xmm2 and xmm3/m128 and store packed maximum values in xmm1 under writemask k1.
T}
T{
EVEX.256.66.0F38.WIG 3C /r VPMAXSB ymm1{k1}{z}, ymm2, ymm3/m256
T}
	C	V/V	AVX512VL AVX512BW	T{
Compare packed signed byte integers in ymm2 and ymm3/m256 and store packed maximum values in ymm1 under writemask k1.
T}
T{
EVEX.512.66.0F38.WIG 3C /r VPMAXSB zmm1{k1}{z}, zmm2, zmm3/m512
T}
	C	V/V	AVX512BW	T{
Compare packed signed byte integers in zmm2 and zmm3/m512 and store packed maximum values in zmm1 under writemask k1.
T}
T{
EVEX.128.66.0F.WIG EE /r VPMAXSW xmm1{k1}{z}, xmm2, xmm3/m128
T}
	C	V/V	AVX512VL AVX512BW	T{
Compare packed signed word integers in xmm2 and xmm3/m128 and store packed maximum values in xmm1 under writemask k1.
T}
T{
EVEX.256.66.0F.WIG EE /r VPMAXSW ymm1{k1}{z}, ymm2, ymm3/m256
T}
	C	V/V	AVX512VL AVX512BW	T{
Compare packed signed word integers in ymm2 and ymm3/m256 and store packed maximum values in ymm1 under writemask k1.
T}
T{
EVEX.512.66.0F.WIG EE /r VPMAXSW zmm1{k1}{z}, zmm2, zmm3/m512
T}
	C	V/V	AVX512BW	T{
Compare packed signed word integers in zmm2 and zmm3/m512 and store packed maximum values in zmm1 under writemask k1.
T}
T{
EVEX.128.66.0F38.W0 3D /r VPMAXSD xmm1 {k1}{z}, xmm2, xmm3/m128/m32bcst
T}
	D	V/V	AVX512VL AVX512F	T{
Compare packed signed dword integers in xmm2 and xmm3/m128/m32bcst and store packed maximum values in xmm1 using writemask k1.
T}
T{
EVEX.256.66.0F38.W0 3D /r VPMAXSD ymm1 {k1}{z}, ymm2, ymm3/m256/m32bcst
T}
	D	V/V	AVX512VL AVX512F	T{
Compare packed signed dword integers in ymm2 and ymm3/m256/m32bcst and store packed maximum values in ymm1 using writemask k1.
T}
T{
EVEX.512.66.0F38.W0 3D /r VPMAXSD zmm1 {k1}{z}, zmm2, zmm3/m512/m32bcst
T}
	D	V/V	AVX512F	T{
Compare packed signed dword integers in zmm2 and zmm3/m512/m32bcst and store packed maximum values in zmm1 using writemask k1.
T}
T{
EVEX.128.66.0F38.W1 3D /r VPMAXSQ xmm1 {k1}{z}, xmm2, xmm3/m128/m64bcst
T}
	D	V/V	AVX512VL AVX512F	T{
Compare packed signed qword integers in xmm2 and xmm3/m128/m64bcst and store packed maximum values in xmm1 using writemask k1.
T}
T{
EVEX.256.66.0F38.W1 3D /r VPMAXSQ ymm1 {k1}{z}, ymm2, ymm3/m256/m64bcst
T}
	D	V/V	AVX512VL AVX512F	T{
Compare packed signed qword integers in ymm2 and ymm3/m256/m64bcst and store packed maximum values in ymm1 using writemask k1.
T}
T{
EVEX.512.66.0F38.W1 3D /r VPMAXSQ zmm1 {k1}{z}, zmm2, zmm3/m512/m64bcst
T}
	D	V/V	AVX512F	T{
Compare packed signed qword integers in zmm2 and zmm3/m512/m64bcst and store packed maximum values in zmm1 using writemask k1.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
B	NA	ModRM:reg (w)	VEX.vvvv (r)	ModRM:r/m (r)	NA
C	Full Mem	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
D	Full	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SS Description
.PP
Performs a SIMD compare of the packed signed byte, word, dword or qword
integers in the second source operand and the first source operand and
returns the maximum value for each pair of integers to the destination
operand.

.PP
Legacy SSE version PMAXSW: The source operand can be an MMX technology
register or a 64\-bit memory location. The destination operand can be an
MMX technology register.

.PP
128\-bit Legacy SSE version: The first source and destination operands
are XMM registers. The second source operand is an XMM register or a
128\-bit memory location. Bits (MAXVL\-1:128) of the corresponding YMM
destination register remain unchanged.

.PP
VEX.128 encoded version: The first source and destination operands are
XMM registers. The second source operand is an XMM register or a 128\-bit
memory location. Bits (MAXVL\-1:128) of the corresponding destination
register are zeroed.

.PP
VEX.256 encoded version: The second source operand can be an YMM
register or a 256\-bit memory location. The first source and destination
operands are YMM registers. Bits (MAXVL\-1:256) of the corresponding
destination register are zeroed.

.PP
EVEX encoded VPMAXSD/Q: The first source operand is a ZMM/YMM/XMM
register; The second source operand is a ZMM/YMM/XMM register, a
512/256/128\-bit memory location or a 512/256/128\-bit vector broadcasted
from a 32/64\-bit memory location. The destination operand is
conditionally updated based on writemask k1.

.PP
EVEX encoded VPMAXSB/W: The first source operand is a ZMM/YMM/XMM
register; The second source operand is a ZMM/YMM/XMM register, a
512/256/128\-bit memory location. The destination operand is
conditionally updated based on writemask k1.

.SS Operation
.SS PMAXSW (64\-bit operands)
.PP
.RS

.nf
IF DEST[15:0] > SRC[15:0]) THEN
    DEST[15:0] ← DEST[15:0];
ELSE
    DEST[15:0] ← SRC[15:0]; FI;
(* Repeat operation for 2nd and 3rd words in source and destination operands *)
IF DEST[63:48] > SRC[63:48]) THEN
    DEST[63:48] ← DEST[63:48];
ELSE
    DEST[63:48] ← SRC[63:48]; FI;

.fi
.RE

.SS PMAXSB (128\-bit Legacy SSE version)
.PP
.RS

.nf
    IF DEST[7:0] >SRC[7:0] THEN
        DEST[7:0] ←DEST[7:0];
    ELSE
        DEST[7:0]←SRC[7:0]; FI;
    (* Repeat operation for 2nd through 15th bytes in source and destination operands *)
    IF DEST[127:120] >SRC[127:120] THEN
        DEST[127:120] ←DEST[127:120];
    ELSE
        DEST[127:120]←SRC[127:120]; FI;
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS VPMAXSB (VEX.128 encoded version)
.PP
.RS

.nf
    IF SRC1[7:0] >SRC2[7:0] THEN
        DEST[7:0] ←SRC1[7:0];
    ELSE
        DEST[7:0]←SRC2[7:0]; FI;
    (* Repeat operation for 2nd through 15th bytes in source and destination operands *)
    IF SRC1[127:120] >SRC2[127:120] THEN
        DEST[127:120] ←SRC1[127:120];
    ELSE
        DEST[127:120]←SRC2[127:120]; FI;
DEST[MAXVL\-1:128] ←0

.fi
.RE

.SS VPMAXSB (VEX.256 encoded version)
.PP
.RS

.nf
    IF SRC1[7:0] >SRC2[7:0] THEN
        DEST[7:0] ←SRC1[7:0];
    ELSE
        DEST[7:0]←SRC2[7:0]; FI;
    (* Repeat operation for 2nd through 31st bytes in source and destination operands *)
    IF SRC1[255:248] >SRC2[255:248] THEN
        DEST[255:248] ←SRC1[255:248];
    ELSE
        DEST[255:248]←SRC2[255:248]; FI;
DEST[MAXVL\-1:256] ←0

.fi
.RE

.SS VPMAXSB (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (16, 128), (32, 256), (64, 512)
FOR j←0 TO KL\-1
    i←j * 8
    IF k1[j] OR *no writemask* THEN
        IF SRC1[i+7:i] > SRC2[i+7:i]
            THEN DEST[i+7:i]←SRC1[i+7:i];
            ELSE DEST[i+7:i]←SRC2[i+7:i];
        FI;
        ELSE
            IF *merging\-masking*
                THEN *DEST[i+7:i] remains unchanged*
                ELSE ; zeroing\-masking
                    DEST[i+7:i] ← 0
            FI
    FI;
ENDFOR;
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS PMAXSW (128\-bit Legacy SSE version)
.PP
.RS

.nf
    IF DEST[15:0] >SRC[15:0] THEN
        DEST[15:0] ←DEST[15:0];
    ELSE
        DEST[15:0]←SRC[15:0]; FI;
    (* Repeat operation for 2nd through 7th words in source and destination operands *)
    IF DEST[127:112] >SRC[127:112] THEN
        DEST[127:112] ←DEST[127:112];
    ELSE
        DEST[127:112]←SRC[127:112]; FI;
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS VPMAXSW (VEX.128 encoded version)
.PP
.RS

.nf
    IF SRC1[15:0] > SRC2[15:0] THEN
        DEST[15:0] ←SRC1[15:0];
    ELSE
        DEST[15:0]←SRC2[15:0]; FI;
    (* Repeat operation for 2nd through 7th words in source and destination operands *)
    IF SRC1[127:112] >SRC2[127:112] THEN
        DEST[127:112] ←SRC1[127:112];
    ELSE
        DEST[127:112]←SRC2[127:112]; FI;
DEST[MAXVL\-1:128] ←0

.fi
.RE

.SS VPMAXSW (VEX.256 encoded version)
.PP
.RS

.nf
    IF SRC1[15:0] > SRC2[15:0] THEN
        DEST[15:0] ←SRC1[15:0];
    ELSE
        DEST[15:0]←SRC2[15:0]; FI;
    (* Repeat operation for 2nd through 15th words in source and destination operands *)
    IF SRC1[255:240] >SRC2[255:240] THEN
        DEST[255:240] ←SRC1[255:240];
    ELSE
        DEST[255:240]←SRC2[255:240]; FI;
DEST[MAXVL\-1:256] ←0

.fi
.RE

.SS VPMAXSW (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (8, 128), (16, 256), (32, 512)
FOR j←0 TO KL\-1
    i←j * 16
    IF k1[j] OR *no writemask* THEN
        IF SRC1[i+15:i] > SRC2[i+15:i]
            THEN DEST[i+15:i]←SRC1[i+15:i];
            ELSE DEST[i+15:i]←SRC2[i+15:i];
        FI;
        ELSE
            IF *merging\-masking*
                THEN *DEST[i+15:i] remains unchanged*
                ELSE ; zeroing\-masking
                    DEST[i+15:i] ← 0
            FI
    FI;
ENDFOR;
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS PMAXSD (128\-bit Legacy SSE version)
.PP
.RS

.nf
    IF DEST[31:0] >SRC[31:0] THEN
        DEST[31:0] ←DEST[31:0];
    ELSE
        DEST[31:0]←SRC[31:0]; FI;
    (* Repeat operation for 2nd through 7th words in source and destination operands *)
    IF DEST[127:96] >SRC[127:96] THEN
        DEST[127:96] ←DEST[127:96];
    ELSE
        DEST[127:96]←SRC[127:96]; FI;
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS VPMAXSD (VEX.128 encoded version)
.PP
.RS

.nf
    IF SRC1[31:0] > SRC2[31:0] THEN
        DEST[31:0] ←SRC1[31:0];
    ELSE
        DEST[31:0]←SRC2[31:0]; FI;
    (* Repeat operation for 2nd through 3rd dwords in source and destination operands *)
    IF SRC1[127:96] > SRC2[127:96] THEN
        DEST[127:96] ←SRC1[127:96];
    ELSE
        DEST[127:96]←SRC2[127:96]; FI;
DEST[MAXVL\-1:128] ←0

.fi
.RE

.SS VPMAXSD (VEX.256 encoded version)
.PP
.RS

.nf
    IF SRC1[31:0] > SRC2[31:0] THEN
        DEST[31:0] ←SRC1[31:0];
    ELSE
        DEST[31:0]←SRC2[31:0]; FI;
    (* Repeat operation for 2nd through 7th dwords in source and destination operands *)
    IF SRC1[255:224] > SRC2[255:224] THEN
        DEST[255:224] ←SRC1[255:224];
    ELSE
        DEST[255:224]←SRC2[255:224]; FI;
DEST[MAXVL\-1:256] ←0

.fi
.RE

.SS VPMAXSD (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (4, 128), (8, 256), (16, 512)
FOR j←0 TO KL\-1
    i←j * 32
    IF k1[j] OR *no writemask*THEN
        IF (EVEX.b = 1) AND (SRC2 *is memory*)
            THEN
                IF SRC1[i+31:i] > SRC2[31:0]
                    THEN DEST[i+31:i]←SRC1[i+31:i];
                    ELSE DEST[i+31:i]←SRC2[31:0];
                FI;
            ELSE
                IF SRC1[i+31:i] > SRC2[i+31:i]
                    THEN DEST[i+31:i]←SRC1[i+31:i];
                    ELSE DEST[i+31:i]←SRC2[i+31:i];
            FI;
        FI;
        ELSE
            IF *merging\-masking* ; merging\-masking
                THEN *DEST[i+31:i] remains unchanged*
                ELSE DEST[i+31:i]←0
                        ; zeroing\-masking
            FI
    FI;
ENDFOR
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VPMAXSQ (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask* THEN
        IF (EVEX.b = 1) AND (SRC2 *is memory*)
            THEN
                IF SRC1[i+63:i] > SRC2[63:0]
                    THEN DEST[i+63:i]←SRC1[i+63:i];
                    ELSE DEST[i+63:i]←SRC2[63:0];
                FI;
            ELSE
                IF SRC1[i+63:i] > SRC2[i+63:i]
                    THEN DEST[i+63:i]←SRC1[i+63:i];
                    ELSE DEST[i+63:i]←SRC2[i+63:i];
            FI;
        FI;
        ELSE
            IF *merging\-masking* ; merging\-masking
                THEN *DEST[i+63:i] remains unchanged*
                ELSE ; zeroing\-masking
                    THEN DEST[i+63:i]←0
            FI
    FI;
ENDFOR;
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VPMAXSB \_\_m512i \_mm512\_max\_epi8( \_\_m512i a, \_\_m512i b);

VPMAXSB \_\_m512i \_mm512\_mask\_max\_epi8(\_\_m512i s, \_\_mmask64 k, \_\_m512i a, \_\_m512i b);

VPMAXSB \_\_m512i \_mm512\_maskz\_max\_epi8( \_\_mmask64 k, \_\_m512i a, \_\_m512i b);

VPMAXSW \_\_m512i \_mm512\_max\_epi16( \_\_m512i a, \_\_m512i b);

VPMAXSW \_\_m512i \_mm512\_mask\_max\_epi16(\_\_m512i s, \_\_mmask32 k, \_\_m512i a, \_\_m512i b);

VPMAXSW \_\_m512i \_mm512\_maskz\_max\_epi16( \_\_mmask32 k, \_\_m512i a, \_\_m512i b);

VPMAXSB \_\_m256i \_mm256\_mask\_max\_epi8(\_\_m256i s, \_\_mmask32 k, \_\_m256i a, \_\_m256i b);

VPMAXSB \_\_m256i \_mm256\_maskz\_max\_epi8( \_\_mmask32 k, \_\_m256i a, \_\_m256i b);

VPMAXSW \_\_m256i \_mm256\_mask\_max\_epi16(\_\_m256i s, \_\_mmask16 k, \_\_m256i a, \_\_m256i b);

VPMAXSW \_\_m256i \_mm256\_maskz\_max\_epi16( \_\_mmask16 k, \_\_m256i a, \_\_m256i b);

VPMAXSB \_\_m128i \_mm\_mask\_max\_epi8(\_\_m128i s, \_\_mmask16 k, \_\_m128i a, \_\_m128i b);

VPMAXSB \_\_m128i \_mm\_maskz\_max\_epi8( \_\_mmask16 k, \_\_m128i a, \_\_m128i b);

VPMAXSW \_\_m128i \_mm\_mask\_max\_epi16(\_\_m128i s, \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSW \_\_m128i \_mm\_maskz\_max\_epi16( \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSD \_\_m256i \_mm256\_mask\_max\_epi32(\_\_m256i s, \_\_mmask16 k, \_\_m256i a, \_\_m256i b);

VPMAXSD \_\_m256i \_mm256\_maskz\_max\_epi32( \_\_mmask16 k, \_\_m256i a, \_\_m256i b);

VPMAXSQ \_\_m256i \_mm256\_mask\_max\_epi64(\_\_m256i s, \_\_mmask8 k, \_\_m256i a, \_\_m256i b);

VPMAXSQ \_\_m256i \_mm256\_maskz\_max\_epi64( \_\_mmask8 k, \_\_m256i a, \_\_m256i b);

VPMAXSD \_\_m128i \_mm\_mask\_max\_epi32(\_\_m128i s, \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSD \_\_m128i \_mm\_maskz\_max\_epi32( \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSQ \_\_m128i \_mm\_mask\_max\_epi64(\_\_m128i s, \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSQ \_\_m128i \_mm\_maskz\_max\_epu64( \_\_mmask8 k, \_\_m128i a, \_\_m128i b);

VPMAXSD \_\_m512i \_mm512\_max\_epi32( \_\_m512i a, \_\_m512i b);

VPMAXSD \_\_m512i \_mm512\_mask\_max\_epi32(\_\_m512i s, \_\_mmask16 k, \_\_m512i a, \_\_m512i b);

VPMAXSD \_\_m512i \_mm512\_maskz\_max\_epi32( \_\_mmask16 k, \_\_m512i a, \_\_m512i b);

VPMAXSQ \_\_m512i \_mm512\_max\_epi64( \_\_m512i a, \_\_m512i b);

VPMAXSQ \_\_m512i \_mm512\_mask\_max\_epi64(\_\_m512i s, \_\_mmask8 k, \_\_m512i a, \_\_m512i b);

VPMAXSQ \_\_m512i \_mm512\_maskz\_max\_epi64( \_\_mmask8 k, \_\_m512i a, \_\_m512i b);

(V)PMAXSB \_\_m128i \_mm\_max\_epi8 ( \_\_m128i a, \_\_m128i b);

(V)PMAXSW \_\_m128i \_mm\_max\_epi16 ( \_\_m128i a, \_\_m128i b)

(V)PMAXSD \_\_m128i \_mm\_max\_epi32 ( \_\_m128i a, \_\_m128i b);

VPMAXSB \_\_m256i \_mm256\_max\_epi8 ( \_\_m256i a, \_\_m256i b);

VPMAXSW \_\_m256i \_mm256\_max\_epi16 ( \_\_m256i a, \_\_m256i b)

VPMAXSD \_\_m256i \_mm256\_max\_epi32 ( \_\_m256i a, \_\_m256i b);

PMAXSW:\_\_m64 \_mm\_max\_pi16(\_\_m64 a, \_\_m64 b)

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
None

.SS Other Exceptions
.PP
Non\-EVEX\-encoded instruction, see Exceptions Type 4.

.PP
EVEX\-encoded VPMAXSD/Q, see Exceptions Type E4.

.PP
EVEX\-encoded VPMAXSB/W, see Exceptions Type E4.nb.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
