.nh
.TH "X86-PSADBW" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
PSADBW - COMPUTE SUM OF ABSOLUTE DIFFERENCES
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
NP 0F F6 /mm1, mm2/m64	A	V/V	SSE	T{
Computes the absolute differences of the packed unsigned byte integers from mm1; differences are then summed to produce an unsigned word integer result.
T}
66 0F F6 /xmm2/m128	A	V/V	SSE2	T{
Computes the absolute differences of the packed unsigned byte integers from xmm1; the 8 low differences and 8 high differences are then summed separately to produce two unsigned word integer results.
T}
T{
VEX.128.66.0F.WIG F6 /r VPSADBW xmm1, xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Computes the absolute differences of the packed unsigned byte integers from xmm2; the 8 low differences and 8 high differences are then summed separately to produce two unsigned word integer results.
T}
T{
VEX.256.66.0F.WIG F6 /r VPSADBW ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX2	T{
Computes the absolute differences of the packed unsigned byte integers from ymm2; then each consecutive 8 differences are summed separately to produce four unsigned word integer results.
T}
T{
EVEX.128.66.0F.WIG F6 /r VPSADBW xmm1, xmm2, xmm3/m128
T}
	C	V/V	AVX512VL AVX512BW	T{
Computes the absolute differences of the packed unsigned byte integers from xmm3 /m128 and xmm2; then each consecutive 8 differences are summed separately to produce four unsigned word integer results.
T}
T{
EVEX.256.66.0F.WIG F6 /r VPSADBW ymm1, ymm2, ymm3/m256
T}
	C	V/V	AVX512VL AVX512BW	T{
Computes the absolute differences of the packed unsigned byte integers from ymm3 /m256 and ymm2; then each consecutive 8 differences are summed separately to produce four unsigned word integer results.
T}
T{
EVEX.512.66.0F.WIG F6 /r VPSADBW zmm1, zmm2, zmm3/m512
T}
	C	V/V	AVX512BW	T{
Computes the absolute differences of the packed unsigned byte integers from zmm3 /m512 and zmm2; then each consecutive 8 differences are summed separately to produce four unsigned word integer results.
T}
.TE

.PP
.RS

.PP
1\&. See note in Section 2.4, “AVX and SSE Instruction Exception
Specification” in the Intel® 64 and IA\-32 Architectures Software
Developer’s Manual, Volume 3A.

.RE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
B	NA	ModRM:reg (w)	VEX.vvvv (r)	ModRM:r/m (r)	NA
C	Full Mem	ModRM:reg (w)	EVEX.vvvv	ModRM:r/m (r)	NA
.TE

.SH DESCRIPTION
.PP
Computes the absolute value of the difference of 8 unsigned byte
integers from the source operand (second operand) and from the
destination operand (first operand). These 8 differences are then summed
to produce an unsigned word integer result that is stored in the
destination operand. Figure 4\-14 shows the operation of the PSADBW
instruction when using 64\-bit operands.

.PP
When operating on 64\-bit operands, the word integer result is stored in
the low word of the destination operand, and the remaining bytes in the
destination operand are cleared to all 0s.

.PP
When operating on 128\-bit operands, two packed results are computed.
Here, the 8 low\-order bytes of the source and destination operands are
operated on to produce a word result that is stored in the low word of
the destination operand, and the 8 high\-order bytes are operated on to
produce a word result that is stored in bits 64 through 79 of the
destination operand. The remaining bytes of the destination operand are
cleared.

.PP
For 256\-bit version, the third group of 8 differences are summed to
produce an unsigned word in bits[143:128] of the destination register
and the fourth group of 8 differences are summed to produce an unsigned
word in bits[207:192] of the destination register. The remaining words
of the destination are set to 0.

.PP
For 512\-bit version, the fifth group result is stored in bits
[271:256] of the destination. The result from the sixth group is
stored in bits [335:320]\&. The results for the seventh and eighth group
are stored respectively in bits [399:384] and bits [463:447],
respectively. The remaining bits in the destination are set to 0.

.PP
In 64\-bit mode and not encoded by VEX/EVEX prefix, using a REX prefix in
the form of REX.R permits this instruction to access additional
registers (XMM8\-XMM15).

.PP
Legacy SSE version: The source operand can be an MMX technology register
or a 64\-bit memory location. The destination operand is an MMX
technology register.

.PP
128\-bit Legacy SSE version: The first source operand and destination
register are XMM registers. The second source operand is an XMM register
or a 128\-bit memory location. Bits (MAXVL\-1:128) of the corresponding
ZMM destination register remain unchanged.

.PP
VEX.128 and EVEX.128 encoded versions: The first source operand and
destination register are XMM registers. The second source operand is an
XMM register or a 128\-bit memory location. Bits (MAXVL\-1:128) of the
corresponding ZMM register are zeroed.

.PP
VEX.256 and EVEX.256 encoded versions: The first source operand and
destination register are YMM registers. The second source operand is an
YMM register or a 256\-bit memory location. Bits (MAXVL\-1:256) of the
corresponding ZMM register are zeroed.

.PP
EVEX.512 encoded version: The first source operand and destination
register are ZMM registers. The second source operand is a ZMM register
or a 512\-bit memory location.

.PP
SRCX7X6X5X4X3X2X1X0DESTY7Y6Y5Y4Y3Y2Y1Y0TEMPABS(X7:Y7)ABS(X6:Y6)ABS(X5:Y5)ABS(X4:Y4)ABS(X3:Y3)ABS(X2:Y2)ABS(X1:Y1)ABS(X0:Y0)DEST00H00H00H00H00H00HSUM(TEMP7...TEMP0)

.PP
Figure 4\-14. PSADBW Instruction Operation Using 64\-bit Operands

.SH OPERATION
.SS VPSADBW (EVEX encoded versions)
.PP
.RS

.nf
VL = 128, 256, 512
TEMP0←ABS(SRC1[7:0] \- SRC2[7:0])
(* Repeat operation for bytes 1 through 15 *)
TEMP15←ABS(SRC1[127:120] \- SRC2[127:120])
DEST[15:0] ←SUM(TEMP0:TEMP7)
DEST[63:16] ← 000000000000H
DEST[79:64] ← SUM(TEMP8:TEMP15)
DEST[127:80] ← 00000000000H
IF VL >= 256
    (* Repeat operation for bytes 16 through 31*)
    TEMP31←ABS(SRC1[255:248] \- SRC2[255:248])
    DEST[143:128] ←SUM(TEMP16:TEMP23)
    DEST[191:144] ← 000000000000H
    DEST[207:192] ← SUM(TEMP24:TEMP31)
    DEST[223:208] ← 00000000000H
FI;
IF VL >= 512
(* Repeat operation for bytes 32 through 63*)
    TEMP63←ABS(SRC1[511:504] \- SRC2[511:504])
    DEST[271:256] ←SUM(TEMP0:TEMP7)
    DEST[319:272] ← 000000000000H
    DEST[335:320] ← SUM(TEMP8:TEMP15)
    DEST[383:336] ← 00000000000H
    DEST[399:384] ←SUM(TEMP16:TEMP23)
    DEST[447:400] ← 000000000000H
    DEST[463:448] ← SUM(TEMP24:TEMP31)
    DEST[511:464] ← 00000000000H
FI;
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VPSADBW (VEX.256 encoded version)
.PP
.RS

.nf
TEMP0←ABS(SRC1[7:0] \- SRC2[7:0])
(* Repeat operation for bytes 2 through 30*)
TEMP31←ABS(SRC1[255:248] \- SRC2[255:248])
DEST[15:0] ←SUM(TEMP0:TEMP7)
DEST[63:16] ← 000000000000H
DEST[79:64] ← SUM(TEMP8:TEMP15)
DEST[127:80] ← 00000000000H
DEST[143:128] ←SUM(TEMP16:TEMP23)
DEST[191:144] ← 000000000000H
DEST[207:192] ← SUM(TEMP24:TEMP31)
DEST[223:208] ← 00000000000H
DEST[MAXVL\-1:256] ← 0

.fi
.RE

.SS VPSADBW (VEX.128 encoded version)
.PP
.RS

.nf
TEMP0←ABS(SRC1[7:0] \- SRC2[7:0])
(* Repeat operation for bytes 2 through 14 *)
TEMP15←ABS(SRC1[127:120] \- SRC2[127:120])
DEST[15:0] ←SUM(TEMP0:TEMP7)
DEST[63:16] ← 000000000000H
DEST[79:64] ← SUM(TEMP8:TEMP15)
DEST[127:80] ← 00000000000H
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS PSADBW (128\-bit Legacy SSE version)
.PP
.RS

.nf
TEMP0←ABS(DEST[7:0] \- SRC[7:0])
(* Repeat operation for bytes 2 through 14 *)
TEMP15←ABS(DEST[127:120] \- SRC[127:120])
DEST[15:0] ←SUM(TEMP0:TEMP7)
DEST[63:16] ← 000000000000H
DEST[79:64] ← SUM(TEMP8:TEMP15)
DEST[127:80] ← 00000000000
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS PSADBW (64\-bit operand)
.PP
.RS

.nf
TEMP0←ABS(DEST[7:0] \- SRC[7:0])
(* Repeat operation for bytes 2 through 6 *)
TEMP7←ABS(DEST[63:56] \- SRC[63:56])
DEST[15:0] ←SUM(TEMP0:TEMP7)
DEST[63:16] ← 000000000000H

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VPSADBW \_\_m512i \_mm512\_sad\_epu8( \_\_m512i a, \_\_m512i b)

PSADBW:\_\_m64 \_mm\_sad\_pu8(\_\_m64 a,\_\_m64 b)

(V)PSADBW:\_\_m128i \_mm\_sad\_epu8(\_\_m128i a, \_\_m128i b)

VPSADBW:\_\_m256i \_mm256\_sad\_epu8( \_\_m256i a, \_\_m256i b)

.fi
.RE

.SH FLAGS AFFECTED
.PP
None.

.SH SIMD FLOATING\-POINT EXCEPTIONS
.PP
None.

.SH OTHER EXCEPTIONS
.PP
Non\-EVEX\-encoded instruction, see Exceptions Type 4.

.PP
EVEX\-encoded instruction, see Exceptions Type E4NF.nb.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
