.nh
.TH "X86-VRCP14SD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
VRCP14SD - COMPUTE APPROXIMATE RECIPROCAL OF SCALAR FLOAT64 VALUE
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp / En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
EVEX.LIG.66.0F38.W1 4D /r VRCP14SD xmm1 {k1}{z}, xmm2, xmm3/m64
T}
	A	V/V	AVX512F	T{
Computes the approximate reciprocal of the scalar double\-precision floating\-point value in xmm3/m64 and stores the result in xmm1 using writemask k1. Also, upper double\-precision floating\-point value (bits
T}
[
127:64
]
) from xmm2 is copied to xmm1
[
127:64
]
\&.
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	Tuple1 Scalar	ModRM:reg (w)	EVEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SS Description
.PP
This instruction performs a SIMD computation of the approximate
reciprocal of the low double\-precision floating\-point value in the
second source operand (the third operand) stores the result in the low
quadword element of the destination operand (the first operand)
according to the writemask k1. Bits (127:64) of the XMM register
destination are copied from corresponding bits in the first source
operand (the second operand). The maximum relative error for this
approximation is less than 2\-14. The source operand can be an XMM
register or a 64\-bit memory location. The destination operand is an XMM
register.

.PP
The VRCP14SD instruction is not affected by the rounding control bits in
the MXCSR register. When a source value is a 0.0, an ∞ with the sign of
the source value is returned. A denormal source value will be treated as
zero only in case of DAZ bit set in MXCSR. Otherwise it is treated
correctly (i.e. not as a 0.0). Underflow results are flushed to zero
only in case of FTZ bit set in MXCSR. Otherwise it will be treated
correctly (i.e. correct underflow result is written) with the sign of
the operand. When a source value is a SNaN or QNaN, the SNaN is
converted to a QNaN or the source QNaN is returned. See Table 5\-22 for
special\-case input values.

.PP
MXCSR exception flags are not affected by this instruction and
floating\-point exceptions are not reported.

.PP
A numerically exact implementation of VRCP14xx can be found at:

.SS https://software.intel.com/en\-us/articles/reference\-implementations\-for\-IA\-approximation\-instructions\-vrcp14\-
.SS vrsqrt14\-vrcp28\-vrsqrt28\-vexp2.
.SS Operation
.SS VRCP14SD (EVEX version)
.PP
.RS

.nf
IF k1[0] OR *no writemask*
        THEN DEST[63:0]←APPROXIMATE(1.0/SRC2[63:0]);
    ELSE
        IF *merging\-masking* ; merging\-masking
            THEN *DEST[63:0] remains unchanged*
            ELSE ; zeroing\-masking
                DEST[63:0] ← 0
        FI;
FI;
DEST[127:64] ← SRC1[127:64]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VRCP14SD \_\_m128d \_mm\_rcp14\_sd( \_\_m128d a, \_\_m128d b);

VRCP14SD \_\_m128d \_mm\_mask\_rcp14\_sd(\_\_m128d s, \_\_mmask8 k, \_\_m128d a, \_\_m128d b);

VRCP14SD \_\_m128d \_mm\_maskz\_rcp14\_sd( \_\_mmask8 k, \_\_m128d a, \_\_m128d b);

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
None

.SS Other Exceptions
.PP
See Exceptions Type E5.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
