.nh
.TH "X86-VCOMPRESSPD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
VCOMPRESSPD - STORE SPARSE PACKED DOUBLE-PRECISION FLOATING-POINT VALUES INTO DENSE MEMORY
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
EVEX.128.66.0F38.W1 8A /r VCOMPRESSPD xmm1/m128 {k1}{z}, xmm2
T}
	A	V/V	AVX512VL AVX512F	T{
Compress packed double\-precision floating\-point values from xmm2 to xmm1/m128 using writemask k1.
T}
T{
EVEX.256.66.0F38.W1 8A /r VCOMPRESSPD ymm1/m256 {k1}{z}, ymm2
T}
	A	V/V	AVX512VL AVX512F	T{
Compress packed double\-precision floating\-point values from ymm2 to ymm1/m256 using writemask k1.
T}
T{
EVEX.512.66.0F38.W1 8A /r VCOMPRESSPD zmm1/m512 {k1}{z}, zmm2
T}
	A	V/V	AVX512F	T{
Compress packed double\-precision floating\-point values from zmm2 using control mask k1 to zmm1/m512.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	Tuple1 Scalar	ModRM:r/m (w)	ModRM:reg (r)	NA	NA
.TE

.SS Description
.PP
Compress (store) up to 8 double\-precision floating\-point values from the
source operand (the second operand) as a contiguous vector to the
destination operand (the first operand) The source operand is a
ZMM/YMM/XMM register, the destination operand can be a ZMM/YMM/XMM
register or a 512/256/128\-bit memory location.

.PP
The opmask register k1 selects the active elements (partial vector or
possibly non\-contiguous if less than 8 active elements) from the source
operand to compress into a contiguous vector. The contiguous vector is
written to the destination starting from the low element of the
destination operand.

.PP
Memory destination version: Only the contiguous vector is written to the
destination memory location. EVEX.z must be zero.

.PP
Register destination version: If the vector length of the contiguous
vector is less than that of the input vector in the source operand, the
upper bits of the destination register are unmodified if EVEX.z is not
set, otherwise the upper bits are zeroed.

.PP
EVEX.vvvv is reserved and must be 1111b otherwise instructions will
#UD.

.PP
Note that the compressed displacement assumes a pre\-scaling (N)
corresponding to the size of one single element instead of the size of
the full vector.

.SS Operation
.SS VCOMPRESSPD (EVEX encoded versions) store form
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
SIZE ← 64
k←0
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask*
        THEN
            DEST[k+SIZE\-1:k]← SRC[i+63:i]
            k←k + SIZE
    FI;
ENDFOR

.fi
.RE

.SS VCOMPRESSPD (EVEX encoded versions) reg\-reg form
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
SIZE ← 64
k←0
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask*
        THEN
                DEST[k+SIZE\-1:k]← SRC[i+63:i]
                k←k + SIZE
    FI;
ENDFOR
IF *merging\-masking*
            THEN *DEST[VL\-1:k] remains unchanged*
            ELSE DEST[VL\-1:k] ← 0
FI
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS Intel C/C++ Compiler Intrinsic Equivalent
.PP
.RS

.nf
VCOMPRESSPD \_\_m512d \_mm512\_mask\_compress\_pd( \_\_m512d s, \_\_mmask8 k, \_\_m512d a);

VCOMPRESSPD \_\_m512d \_mm512\_maskz\_compress\_pd( \_\_mmask8 k, \_\_m512d a);

VCOMPRESSPD void \_mm512\_mask\_compressstoreu\_pd( void * d, \_\_mmask8 k, \_\_m512d a);

VCOMPRESSPD \_\_m256d \_mm256\_mask\_compress\_pd( \_\_m256d s, \_\_mmask8 k, \_\_m256d a);

VCOMPRESSPD \_\_m256d \_mm256\_maskz\_compress\_pd( \_\_mmask8 k, \_\_m256d a);

VCOMPRESSPD void \_mm256\_mask\_compressstoreu\_pd( void * d, \_\_mmask8 k, \_\_m256d a);

VCOMPRESSPD \_\_m128d \_mm\_mask\_compress\_pd( \_\_m128d s, \_\_mmask8 k, \_\_m128d a);

VCOMPRESSPD \_\_m128d \_mm\_maskz\_compress\_pd( \_\_mmask8 k, \_\_m128d a);

VCOMPRESSPD void \_mm\_mask\_compressstoreu\_pd( void * d, \_\_mmask8 k, \_\_m128d a);

.fi
.RE

.SS SIMD Floating\-Point Exceptions
.PP
None

.SS Other Exceptions
.PP
EVEX\-encoded instructions, see Exceptions Type E4.nb.

.TS
allbox;
l l 
l l .
#UD	If EVEX.vvvv != 1111B.
.TE

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
