.nh
.TH "X86-CMPPD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
CMPPD - COMPARE PACKED DOUBLE-PRECISION FLOATING-POINT VALUES
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp / En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
66 0F C2 /r ib CMPPD xmm1, xmm2/m128, imm8
T}
	A	V/V	SSE2	T{
Compare packed double\-precision floating\-point values in xmm2/m128 and xmm1 using bits 2:0 of imm8 as a comparison predicate.
T}
T{
VEX.128.66.0F.WIG C2 /r ib VCMPPD xmm1, xmm2, xmm3/m128, imm8
T}
	B	V/V	AVX	T{
Compare packed double\-precision floating\-point values in xmm3/m128 and xmm2 using bits 4:0 of imm8 as a comparison predicate.
T}
T{
VEX.256.66.0F.WIG C2 /r ib VCMPPD ymm1, ymm2, ymm3/m256, imm8
T}
	B	V/V	AVX	T{
Compare packed double\-precision floating\-point values in ymm3/m256 and ymm2 using bits 4:0 of imm8 as a comparison predicate.
T}
T{
EVEX.128.66.0F.W1 C2 /r ib VCMPPD k1 {k2}, xmm2, xmm3/m128/m64bcst, imm8
T}
	C	V/V	AVX512VL AVX512F	T{
Compare packed double\-precision floating\-point values in xmm3/m128/m64bcst and xmm2 using bits 4:0 of imm8 as a comparison predicate with writemask k2 and leave the result in mask register k1.
T}
T{
EVEX.256.66.0F.W1 C2 /r ib VCMPPD k1 {k2}, ymm2, ymm3/m256/m64bcst, imm8
T}
	C	V/V	AVX512VL AVX512F	T{
Compare packed double\-precision floating\-point values in ymm3/m256/m64bcst and ymm2 using bits 4:0 of imm8 as a comparison predicate with writemask k2 and leave the result in mask register k1.
T}
T{
EVEX.512.66.0F.W1 C2 /r ib VCMPPD k1 {k2}, zmm2, zmm3/m512/m64bcst{sae}, imm8
T}
	C	V/V	AVX512F	T{
Compare packed double\-precision floating\-point values in zmm3/m512/m64bcst and zmm2 using bits 4:0 of imm8 as a comparison predicate with writemask k2 and leave the result in mask register k1.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	Imm8	NA
B	NA	ModRM:reg (w)	VEX.vvvv	ModRM:r/m (r)	Imm8
C	Full	ModRM:reg (w)	EVEX.vvvv	ModRM:r/m (r)	Imm8
.TE

.SH DESCRIPTION
.PP
Performs a SIMD compare of the packed double\-precision floating\-point
values in the second source operand and the first source operand and
returns the results of the comparison to the destination operand. The
comparison predicate operand (immediate byte) specifies the type of
comparison performed on each pair of packed values in the two source
operands.

.PP
EVEX encoded versions: The first source operand (second operand) is a
ZMM/YMM/XMM register. The second source operand can be a ZMM/YMM/XMM
register, a 512/256/128\-bit memory location or a 512/256/128\-bit vector
broadcasted from a 64\-bit memory location. The destination operand
(first operand) is an opmask register. Comparison results are written to
the destination operand under the writemask k2. Each comparison result
is a single mask bit of 1 (comparison true) or 0 (comparison false).

.PP
VEX.256 encoded version: The first source operand (second operand) is a
YMM register. The second source operand (third operand) can be a YMM
register or a 256\-bit memory location. The destination operand (first
operand) is a YMM register. Four comparisons are performed with results
written to the destination operand. The result of each comparison is a
quadword mask of all 1s (comparison true) or all 0s (comparison false).

.PP
128\-bit Legacy SSE version: The first source and destination operand
(first operand) is an XMM register. The second source operand (second
operand) can be an XMM register or 128\-bit memory location. Bits
(MAXVL\-1:128) of the corresponding ZMM destination register remain
unchanged. Two comparisons are performed with results written to bits
127:0 of the destination operand. The result of each comparison is a
quadword mask of all 1s (comparison true) or all 0s (comparison false).

.PP
VEX.128 encoded version: The first source operand (second operand) is an
XMM register. The second source operand (third operand) can be an XMM
register or a 128\-bit memory location. Bits (MAXVL\-1:128) of the
destination ZMM register are zeroed. Two comparisons are performed with
results written to bits 127:0 of the destination operand.

.PP
The comparison predicate operand is an 8\-bit immediate:

.RS
.IP \(bu 2
For instructions encoded using the VEX or EVEX prefix, bits 4:0
define the type of comparison to be performed (see Table 3\-1). Bits
5 through 7 of the immediate are reserved.
.IP \(bu 2
For instruction encodings that do not use VEX prefix, bits 2:0
define the type of comparison to be made (see the first 8 rows of
Table 3\-1). Bits 3 through 7 of the immediate are reserved.

.RE

.PP
Predicate

.PP
imm8 Value

.PP
Description

.PP
Result: A Is 1st Operand, B Is 2nd Operand

.PP
Signals #IA on QNAN

.PP
A \&gt;B

.PP
A\&lt;B

.PP
A=B

.PP
Unordered1

.PP
EQ\_OQ (EQ)

.PP
0H

.PP
Equal (ordered, non\-signaling)

.PP
False

.PP
False

.PP
True

.PP
False

.PP
No

.PP
LT\_OS (LT)

.PP
1H

.PP
Less\-than (ordered, signaling)

.PP
False

.PP
True

.PP
False

.PP
False

.PP
Yes

.PP
LE\_OS (LE)

.PP
2H

.PP
Less\-than\-or\-equal (ordered, signaling)

.PP
False

.PP
True

.PP
True

.PP
False

.PP
Yes

.PP
UNORD\_Q (UNORD)

.PP
3H

.PP
Unordered (non\-signaling)

.PP
False

.PP
False

.PP
False

.PP
True

.PP
No

.PP
NEQ\_UQ (NEQ)

.PP
4H

.PP
Not\-equal (unordered, non\-signaling)

.PP
True

.PP
True

.PP
False

.PP
True

.PP
No

.PP
NLT\_US (NLT)

.PP
5H

.PP
Not\-less\-than (unordered, signaling)

.PP
True

.PP
False

.PP
True

.PP
True

.PP
Yes

.PP
NLE\_US (NLE)

.PP
6H

.PP
Not\-less\-than\-or\-equal (unordered, signaling)

.PP
True

.PP
False

.PP
False

.PP
True

.PP
Yes

.PP
ORD\_Q (ORD)

.PP
7H

.PP
Ordered (non\-signaling)

.PP
True

.PP
True

.PP
True

.PP
False

.PP
No

.PP
EQ\_UQ

.PP
8H

.PP
Equal (unordered, non\-signaling)

.PP
False

.PP
False

.PP
True

.PP
True

.PP
No

.PP
NGE\_US (NGE)

.PP
9H

.PP
Not\-greater\-than\-or\-equal (unordered, signaling)

.PP
False

.PP
True

.PP
False

.PP
True

.PP
Yes

.PP
NGT\_US (NGT)

.PP
AH

.PP
Not\-greater\-than (unordered, signaling)

.PP
False

.PP
True

.PP
True

.PP
True

.PP
Yes

.PP
FALSE\_OQ(FALSE)

.PP
BH

.PP
False (ordered, non\-signaling)

.PP
False

.PP
False

.PP
False

.PP
False

.PP
No

.PP
NEQ\_OQ

.PP
CH

.PP
Not\-equal (ordered, non\-signaling)

.PP
True

.PP
True

.PP
False

.PP
False

.PP
No

.PP
GE\_OS (GE)

.PP
DH

.PP
Greater\-than\-or\-equal (ordered, signaling)

.PP
True

.PP
False

.PP
True

.PP
False

.PP
Yes

.PP
GT\_OS (GT)

.PP
EH

.PP
Greater\-than (ordered, signaling)

.PP
True

.PP
False

.PP
False

.PP
False

.PP
Yes

.PP
TRUE\_UQ(TRUE)

.PP
FH

.PP
True (unordered, non\-signaling)

.PP
True

.PP
True

.PP
True

.PP
True

.PP
No

.PP
EQ\_OS

.PP
10H

.PP
Equal (ordered, signaling)

.PP
False

.PP
False

.PP
True

.PP
False

.PP
Yes

.PP
LT\_OQ

.PP
11H

.PP
Less\-than (ordered, nonsignaling)

.PP
False

.PP
True

.PP
False

.PP
False

.PP
No

.PP
LE\_OQ

.PP
12H

.PP
Less\-than\-or\-equal (ordered, nonsignaling)

.PP
False

.PP
True

.PP
True

.PP
False

.PP
No

.PP
UNORD\_S

.PP
13H

.PP
Unordered (signaling)

.PP
False

.PP
False

.PP
False

.PP
True

.PP
Yes

.PP
NEQ\_US

.PP
14H

.PP
Not\-equal (unordered, signaling)

.PP
True

.PP
True

.PP
False

.PP
True

.PP
Yes

.PP
NLT\_UQ

.PP
15H

.PP
Not\-less\-than (unordered, nonsignaling)

.PP
True

.PP
False

.PP
True

.PP
True

.PP
No

.PP
NLE\_UQ

.PP
16H

.PP
Not\-less\-than\-or\-equal (unordered, nonsignaling)

.PP
True

.PP
False

.PP
False

.PP
True

.PP
No

.PP
ORD\_S

.PP
17H

.PP
Ordered (signaling)

.PP
True

.PP
True

.PP
True

.PP
False

.PP
Yes

.PP
EQ\_US

.PP
18H

.PP
Equal (unordered, signaling)

.PP
False

.PP
False

.PP
True

.PP
True

.PP
Yes

.PP
NGE\_UQ

.PP
19H

.PP
Not\-greater\-than\-or\-equal (unordered, non\-signaling)

.PP
False

.PP
True

.PP
False

.PP
True

.PP
No

.PP
NGT\_UQ

.PP
1AH

.PP
Not\-greater\-than (unordered, nonsignaling)

.PP
False

.PP
True

.PP
True

.PP
True

.PP
No

.PP
FALSE\_OS

.PP
1BH

.PP
False (ordered, signaling)

.PP
False

.PP
False

.PP
False

.PP
False

.PP
Yes

.PP
NEQ\_OS

.PP
1CH

.PP
Not\-equal (ordered, signaling)

.PP
True

.PP
True

.PP
False

.PP
False

.PP
Yes

.PP
GE\_OQ

.PP
1DH

.PP
Greater\-than\-or\-equal (ordered, nonsignaling)

.PP
True

.PP
False

.PP
True

.PP
False

.PP
No

.PP
GT\_OQ

.PP
1EH

.PP
Greater\-than (ordered, nonsignaling)

.PP
True

.PP
False

.PP
False

.PP
False

.PP
No

.PP
TRUE\_US

.PP
1FH

.PP
True (unordered, signaling)

.PP
True

.PP
True

.PP
True

.PP
True

.PP
Yes

.PP
Table 3\-1. Comparison Predicate for CMPPD and CMPPS Instructions

.PP
.RS

.PP
1\&. If either operand A or B is a NAN.

.RE

.PP
The unordered relationship is true when at least one of the two source
operands being compared is a NaN; the ordered relationship is true when
neither source operand is a NaN.

.PP
A subsequent computational instruction that uses the mask result in the
destination operand as an input operand will not generate an exception,
because a mask of all 0s corresponds to a floating\-point value of +0.0
and a mask of all 1s corresponds to a QNaN.

.PP
Note that processors with “CPUID.1H:ECX.AVX =0” do not implement the
“greater\-than”, “greater\-than\-or\-equal”, “not\-greater than”, and
“not\-greater\-than\-or\-equal relations” predicates. These comparisons can
be made either by using the inverse relationship (that is, use the
“not\-less\-than\-or\-equal” to make a “greater\-than” comparison) or by
using software emulation. When using software emulation, the program
must swap the operands (copying registers when necessary to protect the
data that will now be in the destination), and then perform the compare
using a different predicate. The predicate to be used for these
emulations is listed in the first 8 rows of Table 3\-7 (Intel 64 and
IA\-32 Architectures Software Developer’s Manual Volume 2A) under the
heading Emulation.

.PP
Compilers and assemblers may implement the following two\-operand
pseudo\-ops in addition to the three\-operand CMPPD instruction, for
processors with “CPUID.1H:ECX.AVX =0”. See Table 3\-2. Compiler should
treat reserved Imm8 values as illegal syntax.

.TS
allbox;
l l 
l l .
\fB\fCPseudo\-Op\fR	\fB\fCCMPPD Implementation\fR
CMPEQPD xmm1, xmm2	CMPPD xmm1, xmm2, 0
CMPLTPD xmm1, xmm2	CMPPD xmm1, xmm2, 1
CMPLEPD xmm1, xmm2	CMPPD xmm1, xmm2, 2
CMPUNORDPD xmm1, xmm2	CMPPD xmm1, xmm2, 3
CMPNEQPD xmm1, xmm2	CMPPD xmm1, xmm2, 4
CMPNLTPD xmm1, xmm2	CMPPD xmm1, xmm2, 5
CMPNLEPD xmm1, xmm2	CMPPD xmm1, xmm2, 6
CMPORDPD xmm1, xmm2	CMPPD xmm1, xmm2, 7
.TE

.PP
Table 3\-2. Pseudo\-Op and CMPPD Implementation

.PP
The greater\-than relations that the processor does not implement require
more than one instruction to emulate in software and therefore should
not be implemented as pseudo\-ops. (For these, the programmer should
reverse the operands of the corresponding less than relations and use
move instructions to ensure that the mask is moved to the correct
destination register and that the source operand is left intact.)

.PP
Processors with “CPUID.1H:ECX.AVX =1” implement the full complement of
32 predicates shown in Table 3\-3, where the notations of reg1 reg2, and
reg3 represent either XMM registers or YMM registers. Compiler should
treat reserved Imm8 values as illegal

.PP
syntax. Alternately, intrinsics can map the pseudo\-ops to pre\-defined
constants to support a simpler intrinsic interface. Compilers and
assemblers may implement three\-operand pseudo\-ops for EVEX encoded
VCMPPD instructions in a similar fashion by extending the syntax listed
in Table 3\-3.

.TS
allbox;
l l 
l l .
\fB\fCPseudo\-Op\fR	\fB\fCCMPPD Implementation\fR
VCMPEQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0
VCMPLTPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1
VCMPLEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 2
VCMPUNORDPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 3
VCMPNEQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 4
VCMPNLTPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 5
VCMPNLEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 6
VCMPORDPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 7
VCMPEQ\_UQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 8
VCMPNGEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 9
VCMPNGTPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0AH
VCMPFALSEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0BH
VCMPNEQ\_OQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0CH
VCMPGEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0DH
VCMPGTPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0EH
VCMPTRUEPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 0FH
VCMPEQ\_OSPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 10H
VCMPLT\_OQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 11H
VCMPLE\_OQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 12H
VCMPUNORD\_SPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 13H
VCMPNEQ\_USPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 14H
VCMPNLT\_UQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 15H
VCMPNLE\_UQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 16H
VCMPORD\_SPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 17H
VCMPEQ\_USPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 18H
VCMPNGE\_UQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 19H
VCMPNGT\_UQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1AH
VCMPFALSE\_OSPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1BH
VCMPNEQ\_OSPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1CH
VCMPGE\_OQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1DH
VCMPGT\_OQPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1EH
VCMPTRUE\_USPD reg1, reg2, reg3	VCMPPD reg1, reg2, reg3, 1FH
.TE

.PP
Table 3\-3. Pseudo\-Op and VCMPPD Implementation

.SH OPERATION
.PP
.RS

.nf
CASE (COMPARISON PREDICATE) OF
0: OP3←EQ\_OQ; OP5←EQ\_OQ;
    1: OP3←LT\_OS; OP5←LT\_OS;
    2: OP3←LE\_OS; OP5←LE\_OS;
    3: OP3←UNORD\_Q; OP5←UNORD\_Q;
    4: OP3←NEQ\_UQ; OP5←NEQ\_UQ;
    5: OP3←NLT\_US; OP5←NLT\_US;
    6: OP3←NLE\_US; OP5←NLE\_US;
    7: OP3←ORD\_Q; OP5←ORD\_Q;
    8: OP5←EQ\_UQ;
    9: OP5←NGE\_US;
    10: OP5←NGT\_US;
    11: OP5←FALSE\_OQ;
    12: OP5←NEQ\_OQ;
    13: OP5←GE\_OS;
    14: OP5←GT\_OS;
    15: OP5←TRUE\_UQ;
    16: OP5←EQ\_OS;
    17: OP5←LT\_OQ;
    18: OP5←LE\_OQ;
    19: OP5←UNORD\_S;
    20: OP5←NEQ\_US;
    21: OP5←NLT\_UQ;
    22: OP5←NLE\_UQ;
    23: OP5←ORD\_S;
    24: OP5←EQ\_US;
    25: OP5←NGE\_UQ;
    26: OP5←NGT\_UQ;
    27: OP5←FALSE\_OS;
    28: OP5←NEQ\_OS;
    29: OP5←GE\_OQ;
    30: OP5←GT\_OQ;
    31: OP5←TRUE\_US;
    DEFAULT: Reserved;
ESAC;

.fi
.RE

.SS VCMPPD (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
FOR j←0 TO KL\-1
    i←j * 64
    IF k2[j] OR *no writemask*
        THEN
            IF (EVEX.b = 1) AND (SRC2 *is memory*)
                THEN
                    CMP←SRC1[i+63:i] OP5 SRC2[63:0]
                ELSE
                    CMP←SRC1[i+63:i] OP5 SRC2[i+63:i]
            FI;
            IF CMP = TRUE
                THEN DEST[j]←1;
                ELSE DEST[j]←0; FI;
        ELSE DEST[j]←0
                        ; zeroing\-masking only
    FI;
ENDFOR
DEST[MAX\_KL\-1:KL] ← 0

.fi
.RE

.SS VCMPPD (VEX.256 encoded version)
.PP
.RS

.nf
CMP0←SRC1[63:0] OP5 SRC2[63:0];
CMP1←SRC1[127:64] OP5 SRC2[127:64];
CMP2←SRC1[191:128] OP5 SRC2[191:128];
CMP3←SRC1[255:192] OP5 SRC2[255:192];
IF CMP0 = TRUE
    THEN DEST[63:0]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[63:0]←0000000000000000H; FI;
IF CMP1 = TRUE
    THEN DEST[127:64]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[127:64]←0000000000000000H; FI;
IF CMP2 = TRUE
    THEN DEST[191:128]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[191:128]←0000000000000000H; FI;
IF CMP3 = TRUE
    THEN DEST[255:192]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[255:192]←0000000000000000H; FI;
DEST[MAXVL\-1:256] ← 0

.fi
.RE

.SS VCMPPD (VEX.128 encoded version)
.PP
.RS

.nf
CMP0←SRC1[63:0] OP5 SRC2[63:0];
CMP1←SRC1[127:64] OP5 SRC2[127:64];
IF CMP0 = TRUE
    THEN DEST[63:0]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[63:0]←0000000000000000H; FI;
IF CMP1 = TRUE
    THEN DEST[127:64]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[127:64]←0000000000000000H; FI;
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS CMPPD (128\-bit Legacy SSE version)
.PP
.RS

.nf
CMP0←SRC1[63:0] OP3 SRC2[63:0];
CMP1←SRC1[127:64] OP3 SRC2[127:64];
IF CMP0 = TRUE
    THEN DEST[63:0]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[63:0]←0000000000000000H; FI;
IF CMP1 = TRUE
    THEN DEST[127:64]←FFFFFFFFFFFFFFFFH;
    ELSE DEST[127:64]←0000000000000000H; FI;
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SH INTEL C/C++ COMPILER INTRINSIC EQUIVALENT
.PP
.RS

.nf
VCMPPD \_\_mmask8 \_mm512\_cmp\_pd\_mask( \_\_m512d a, \_\_m512d b, int imm);

VCMPPD \_\_mmask8 \_mm512\_cmp\_round\_pd\_mask( \_\_m512d a, \_\_m512d b, int imm, int sae);

VCMPPD \_\_mmask8 \_mm512\_mask\_cmp\_pd\_mask( \_\_mmask8 k1, \_\_m512d a, \_\_m512d b, int imm);

VCMPPD \_\_mmask8 \_mm512\_mask\_cmp\_round\_pd\_mask( \_\_mmask8 k1, \_\_m512d a, \_\_m512d b, int imm, int sae);

VCMPPD \_\_mmask8 \_mm256\_cmp\_pd\_mask( \_\_m256d a, \_\_m256d b, int imm);

VCMPPD \_\_mmask8 \_mm256\_mask\_cmp\_pd\_mask( \_\_mmask8 k1, \_\_m256d a, \_\_m256d b, int imm);

VCMPPD \_\_mmask8 \_mm\_cmp\_pd\_mask( \_\_m128d a, \_\_m128d b, int imm);

VCMPPD \_\_mmask8 \_mm\_mask\_cmp\_pd\_mask( \_\_mmask8 k1, \_\_m128d a, \_\_m128d b, int imm);

VCMPPD \_\_m256 \_mm256\_cmp\_pd(\_\_m256d a, \_\_m256d b, int imm)

(V)CMPPD \_\_m128 \_mm\_cmp\_pd(\_\_m128d a, \_\_m128d b, int imm)

.fi
.RE

.SH SIMD FLOATING\-POINT EXCEPTIONS
.PP
Invalid if SNaN operand and invalid if QNaN and predicate as listed in
Table 3\-1.

.PP
Denormal

.SH OTHER EXCEPTIONS
.PP
VEX\-encoded instructions, see Exceptions Type 2.

.PP
EVEX\-encoded instructions, see Exceptions Type E2.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
