.nh
.TH "X86-HADDPS" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
HADDPS - PACKED SINGLE-FP HORIZONTAL ADD
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32\-bit Mode\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
F2 0F 7C /xmm1, xmm2/m128	RM	V/V	SSE3	T{
Horizontal add packed single\-precision floating\-point values from xmm1.
T}
T{
VEX.128.F2.0F.WIG 7C /r VHADDPS xmm1, xmm2, xmm3/m128
T}
	RVM	V/V	AVX	T{
Horizontal add packed single\-precision floating\-point values from xmm2 and xmm3/mem.
T}
T{
VEX.256.F2.0F.WIG 7C /r VHADDPS ymm1, ymm2, ymm3/m256
T}
	RVM	V/V	AVX	T{
Horizontal add packed single\-precision floating\-point values from ymm2 and ymm3/mem.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l 
l l l l l .
Op/En	Operand 1	Operand 2	Operand 3	Operand 4
RM	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
RVM	ModRM:reg (w)	VEX.vvvv (r)	ModRM:r/m (r)	NA
.TE

.SH DESCRIPTION
.PP
Adds the single\-precision floating\-point values in the first and second
dwords of the destination operand and stores the result in the first
dword of the destination operand.

.PP
Adds single\-precision floating\-point values in the third and fourth
dword of the destination operand and stores the result in the second
dword of the destination operand.

.PP
Adds single\-precision floating\-point values in the first and second
dword of the source operand and stores the result in the third dword of
the destination operand.

.PP
Adds single\-precision floating\-point values in the third and fourth
dword of the source operand and stores the result in the fourth dword of
the destination operand.

.PP
In 64\-bit mode, use of the REX.R prefix permits this instruction to
access additional registers (XMM8\-XMM15).

.PP
See Figure 3\-19 for VHADDPS.

.PP
HADDPS xmm1,
xmm2/m128xmm2/[127:96][95:64][63:32][31:0]m128xmm1[95:64][63:32][31:0]xmm2/m128xmm2/m128RESULT:xmm1[95:64]
+xmm1[31:0] +[95:64] + xmm2/[31:0] +
xmm2/xmm1xmm1[127:96]xmm1[63:32]m128[127:96]m128[63:32][127:96][95:64][63:32][31:0]

.PP
Figure 3\-18. HADDPS—Packed Single\-FP Horizontal Add

.PP
X6X5X4X3X2X1X0SRC1Y6Y5Y4Y3Y2Y1Y0SRC2Y2+Y3Y0+Y1DESTY6+Y7Y4+Y5X6+X7X4+X5X2+X3X0+X1

.PP
Figure 3\-19. VHADDPS operation

.PP
128\-bit Legacy SSE version: The second source can be an XMM register or
an 128\-bit memory location. The destination is not distinct from the
first source XMM register and the upper bits (MAXVL\-1:128) of the
corresponding YMM register destination are unmodified.

.PP
VEX.128 encoded version: the first source operand is an XMM register or
128\-bit memory location. The destination operand is an XMM register. The
upper bits (MAXVL\-1:128) of the corresponding YMM register destination
are zeroed.

.PP
VEX.256 encoded version: The first source operand is a YMM register. The
second source operand can be a YMM register or a 256\-bit memory
location. The destination operand is a YMM register.

.SH OPERATION
.SS HADDPS (128\-bit Legacy SSE version)
.PP
.RS

.nf
DEST[31:0]←SRC1[63:32] + SRC1[31:0]
DEST[63:32]←SRC1[127:96] + SRC1[95:64]
DEST[95:64]←SRC2[63:32] + SRC2[31:0]
DEST[127:96]←SRC2[127:96] + SRC2[95:64]
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SS VHADDPS (VEX.128 encoded version)
.PP
.RS

.nf
DEST[31:0]←SRC1[63:32] + SRC1[31:0]
DEST[63:32]←SRC1[127:96] + SRC1[95:64]
DEST[95:64]←SRC2[63:32] + SRC2[31:0]
DEST[127:96]←SRC2[127:96] + SRC2[95:64]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS VHADDPS (VEX.256 encoded version)
.PP
.RS

.nf
DEST[31:0]←SRC1[63:32] + SRC1[31:0]
DEST[63:32]←SRC1[127:96] + SRC1[95:64]
DEST[95:64]←SRC2[63:32] + SRC2[31:0]
DEST[127:96]←SRC2[127:96] + SRC2[95:64]
DEST[159:128]←SRC1[191:160] + SRC1[159:128]
DEST[191:160]←SRC1[255:224] + SRC1[223:192]
DEST[223:192]←SRC2[191:160] + SRC2[159:128]
DEST[255:224]←SRC2[255:224] + SRC2[223:192]

.fi
.RE

.SH INTEL C/C++ COMPILER INTRINSIC EQUIVALENT
.PP
.RS

.nf
HADDPS: \_\_m128 \_mm\_hadd\_ps (\_\_m128 a, \_\_m128 b);

VHADDPS: \_\_m256 \_mm256\_hadd\_ps (\_\_m256 a, \_\_m256 b);

.fi
.RE

.SH EXCEPTIONS
.PP
When the source operand is a memory operand, the operand must be aligned
on a 16\-byte boundary or a general\-protection exception (#GP) will be
generated.

.SH NUMERIC EXCEPTIONS
.PP
Overflow, Underflow, Invalid, Precision, Denormal

.SH OTHER EXCEPTIONS
.PP
See Exceptions Type 2.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
