.nh
.TH "X86-ANDNPD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
ANDNPD - BITWISE LOGICAL AND NOT OF PACKED DOUBLE PRECISION FLOATING-POINT VALUES
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
66 0F 55 /r ANDNPD xmm1, xmm2/m128
T}
	A	V/V	SSE2	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in xmm1 and xmm2/mem.
T}
T{
VEX.128.66.0F 55 /r VANDNPD xmm1, xmm2, xmm3/m128
T}
	B	V/V	AVX	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in xmm2 and xmm3/mem.
T}
T{
VEX.256.66.0F 55/r VANDNPD ymm1, ymm2, ymm3/m256
T}
	B	V/V	AVX	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in ymm2 and ymm3/mem.
T}
T{
EVEX.128.66.0F.W1 55 /r VANDNPD xmm1 {k1}{z}, xmm2, xmm3/m128/m64bcst
T}
	C	V/V	AVX512VL AVX512DQ	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in xmm2 and xmm3/m128/m64bcst subject to writemask k1.
T}
T{
EVEX.256.66.0F.W1 55 /r VANDNPD ymm1 {k1}{z}, ymm2, ymm3/m256/m64bcst
T}
	C	V/V	AVX512VL AVX512DQ	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in ymm2 and ymm3/m256/m64bcst subject to writemask k1.
T}
T{
EVEX.512.66.0F.W1 55 /r VANDNPD zmm1 {k1}{z}, zmm2, zmm3/m512/m64bcst
T}
	C	V/V	AVX512DQ	T{
Return the bitwise logical AND NOT of packed double\-precision floating\-point values in zmm2 and zmm3/m512/m64bcst subject to writemask k1.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l l 
l l l l l l .
Op/En	Tuple Type	Operand 1	Operand 2	Operand 3	Operand 4
A	NA	ModRM:reg (r, w)	ModRM:r/m (r)	NA	NA
B	NA	ModRM:reg (w)	VEX.vvvv	ModRM:r/m (r)	NA
C	Full	ModRM:reg (w)	EVEX.vvvv	ModRM:r/m (r)	NA
.TE

.SH DESCRIPTION
.PP
Performs a bitwise logical AND NOT of the two, four or eight packed
double\-precision floating\-point values from the first source operand and
the second source operand, and stores the result in the destination
operand.

.PP
EVEX encoded versions: The first source operand is a ZMM/YMM/XMM
register. The second source operand can be a ZMM/YMM/XMM register, a
512/256/128\-bit memory location, or a 512/256/128\-bit vector broadcasted
from a 64\-bit memory location. The destination operand is a ZMM/YMM/XMM
register conditionally updated with writemask k1.

.PP
VEX.256 encoded version: The first source operand is a YMM register. The
second source operand is a YMM register or a 256\-bit memory location.
The destination operand is a YMM register. The upper bits (MAXVL\-1:256)
of the corresponding ZMM register destination are zeroed.

.PP
VEX.128 encoded version: The first source operand is an XMM register.
The second source operand is an XMM register or 128\-bit memory location.
The destination operand is an XMM register. The upper bits (MAXVL\-1:128)
of the corresponding ZMM register destination are zeroed.

.PP
128\-bit Legacy SSE version: The second source can be an XMM register or
an 128\-bit memory location. The destination is not distinct from the
first source XMM register and the upper bits (MAXVL\-1:128) of the
corresponding register destination are unmodified.

.SH OPERATION
.SS VANDNPD (EVEX encoded versions)
.PP
.RS

.nf
(KL, VL) = (2, 128), (4, 256), (8, 512)
FOR j←0 TO KL\-1
    i←j * 64
    IF k1[j] OR *no writemask*
            IF (EVEX.b == 1) AND (SRC2 *is memory*)
                THEN
                    DEST[i+63:i]←(NOT(SRC1[i+63:i])) BITWISE AND SRC2[63:0]
                ELSE
                    DEST[i+63:i]←(NOT(SRC1[i+63:i])) BITWISE AND SRC2[i+63:i]
            FI;
        ELSE
            IF *merging\-masking* ; merging\-masking
                THEN *DEST[i+63:i] remains unchanged*
                ELSE ; zeroing\-masking
                    DEST[i+63:i] = 0
            FI;
    FI;
ENDFOR
DEST[MAXVL\-1:VL] ← 0

.fi
.RE

.SS VANDNPD (VEX.256 encoded version)
.PP
.RS

.nf
DEST[63:0]←(NOT(SRC1[63:0])) BITWISE AND SRC2[63:0]
DEST[127:64]←(NOT(SRC1[127:64])) BITWISE AND SRC2[127:64]
DEST[191:128]←(NOT(SRC1[191:128])) BITWISE AND SRC2[191:128]
DEST[255:192]←(NOT(SRC1[255:192])) BITWISE AND SRC2[255:192]
DEST[MAXVL\-1:256] ← 0

.fi
.RE

.SS VANDNPD (VEX.128 encoded version)
.PP
.RS

.nf
DEST[63:0]←(NOT(SRC1[63:0])) BITWISE AND SRC2[63:0]
DEST[127:64]←(NOT(SRC1[127:64])) BITWISE AND SRC2[127:64]
DEST[MAXVL\-1:128] ← 0

.fi
.RE

.SS ANDNPD (128\-bit Legacy SSE version)
.PP
.RS

.nf
DEST[63:0]←(NOT(DEST[63:0])) BITWISE AND SRC[63:0]
DEST[127:64]←(NOT(DEST[127:64])) BITWISE AND SRC[127:64]
DEST[MAXVL\-1:128] (Unmodified)

.fi
.RE

.SH INTEL C/C++ COMPILER INTRINSIC EQUIVALENT
.PP
.RS

.nf
VANDNPD \_\_m512d \_mm512\_andnot\_pd (\_\_m512d a, \_\_m512d b);

VANDNPD \_\_m512d \_mm512\_mask\_andnot\_pd (\_\_m512d s, \_\_mmask8 k, \_\_m512d a, \_\_m512d b);

VANDNPD \_\_m512d \_mm512\_maskz\_andnot\_pd (\_\_mmask8 k, \_\_m512d a, \_\_m512d b);

VANDNPD \_\_m256d \_mm256\_mask\_andnot\_pd (\_\_m256d s, \_\_mmask8 k, \_\_m256d a, \_\_m256d b);

VANDNPD \_\_m256d \_mm256\_maskz\_andnot\_pd (\_\_mmask8 k, \_\_m256d a, \_\_m256d b);

VANDNPD \_\_m128d \_mm\_mask\_andnot\_pd (\_\_m128d s, \_\_mmask8 k, \_\_m128d a, \_\_m128d b);

VANDNPD \_\_m128d \_mm\_maskz\_andnot\_pd (\_\_mmask8 k, \_\_m128d a, \_\_m128d b);

VANDNPD \_\_m256d \_mm256\_andnot\_pd (\_\_m256d a, \_\_m256d b);

ANDNPD \_\_m128d \_mm\_andnot\_pd (\_\_m128d a, \_\_m128d b);

.fi
.RE

.SH SIMD FLOATING\-POINT EXCEPTIONS
.PP
None

.SH OTHER EXCEPTIONS
.PP
VEX\-encoded instruction, see Exceptions Type 4.

.PP
EVEX\-encoded instruction, see Exceptions Type E4.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
