.nh
.TH "X86-CVTPD2PI" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
CVTPD2PI - CONVERT PACKED DOUBLE-PRECISION FP VALUES TO PACKED DWORD INTEGERS
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64\-Bit Mode\fR	\fB\fCCompat/Leg Mode\fR	\fB\fCDescription\fR
66 0F 2D /xmm/m128	RM	Valid	Valid	T{
Convert two packed double\-precision floating\-point values from mm.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l l l 
l l l l l .
Op/En	Operand 1	Operand 2	Operand 3	Operand 4
RM	ModRM:reg (w)	ModRM:r/m (r)	NA	NA
.TE

.SH DESCRIPTION
.PP
Converts two packed double\-precision floating\-point values in the source
operand (second operand) to two packed signed doubleword integers in the
destination operand (first operand).

.PP
The source operand can be an XMM register or a 128\-bit memory location.
The destination operand is an MMX technology register.

.PP
When a conversion is inexact, the value returned is rounded according to
the rounding control bits in the MXCSR register. If a converted result
is larger than the maximum signed doubleword integer, the floating\-point
invalid exception is raised, and if this exception is masked, the
indefinite integer value (80000000H) is returned.

.PP
This instruction causes a transition from x87 FPU to MMX technology
operation (that is, the x87 FPU top\-of\-stack pointer is set to 0 and the
x87 FPU tag word is set to all 0s [valid]). If this instruction is
executed while an x87 FPU floating\-point exception is pending, the
exception is handled before the CVTPD2PI instruction is executed.

.PP
In 64\-bit mode, use of the REX.R prefix permits this instruction to
access additional registers (XMM8\-XMM15).

.SH OPERATION
.PP
.RS

.nf
DEST[31:0] ← Convert\_Double\_Precision\_Floating\_Point\_To\_Integer32(SRC[63:0]);
DEST[63:32] ← Convert\_Double\_Precision\_Floating\_Point\_To\_Integer32(SRC[127:64]);

.fi
.RE

.SH INTEL C/C++ COMPILER INTRINSIC EQUIVALENT
.PP
.RS

.nf
CVTPD1PI: \_\_m64 \_mm\_cvtpd\_pi32(\_\_m128d a)

.fi
.RE

.SH SIMD FLOATING\-POINT EXCEPTIONS
.PP
Invalid, Precision.

.SH OTHER EXCEPTIONS
.PP
See Table 22\-4, “Exception Conditions
for Legacy SIMD/MMX Instructions with FP Exception and 16\-Byte
Alignment,” in the Intel® 64 and IA\-32 Architectures Software
Developer’s Manual, Volume 3B.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
