.nh
.TH "X86-KNOTW-KNOTB-KNOTQ-KNOTD" "7" "May 2019" "TTMO" "Intel x86-64 ISA Manual"
.SH NAME
KNOTW-KNOTB-KNOTQ-KNOTD - NOT MASK REGISTER
.TS
allbox;
l l l l l 
l l l l l .
\fB\fCOpcode/Instruction\fR	\fB\fCOp/En\fR	\fB\fC64/32 bit Mode Support\fR	\fB\fCCPUID Feature Flag\fR	\fB\fCDescription\fR
T{
VEX.L0.0F.W0 44 /r KNOTW k1, k2
T}
	RR	V/V	AVX512F	T{
Bitwise NOT of 16 bits mask k2.
T}
T{
VEX.L0.66.0F.W0 44 /r KNOTB k1, k2
T}
	RR	V/V	AVX512DQ	Bitwise NOT of 8 bits mask k2.
T{
VEX.L0.0F.W1 44 /r KNOTQ k1, k2
T}
	RR	V/V	AVX512BW	T{
Bitwise NOT of 64 bits mask k2.
T}
T{
VEX.L0.66.0F.W1 44 /r KNOTD k1, k2
T}
	RR	V/V	AVX512BW	T{
Bitwise NOT of 32 bits mask k2.
T}
.TE

.SH INSTRUCTION OPERAND ENCODING
.TS
allbox;
l l l 
l l l .
Op/En	Operand 1	Operand 2
RR	ModRM:reg (w)	ModRM:r/m (r, ModRM:
[
7:6
]
 must be 11b)
.TE

.SH DESCRIPTION
.PP
Performs a bitwise NOT of vector mask k2 and writes the result into
vector mask k1.

.SH OPERATION
.SS KNOTW
.PP
.RS

.nf
DEST[15:0]←BITWISE NOT SRC[15:0]
DEST[MAX\_KL\-1:16] ← 0

.fi
.RE

.SS KNOTB
.PP
.RS

.nf
DEST[7:0]←BITWISE NOT SRC[7:0]
DEST[MAX\_KL\-1:8] ← 0

.fi
.RE

.SS KNOTQ
.PP
.RS

.nf
DEST[63:0]←BITWISE NOT SRC[63:0]
DEST[MAX\_KL\-1:64] ← 0

.fi
.RE

.SS KNOTD
.PP
.RS

.nf
DEST[31:0]←BITWISE NOT SRC[31:0]
DEST[MAX\_KL\-1:32] ← 0

.fi
.RE

.SH INTEL C/C++ COMPILER INTRINSIC EQUIVALENT
.PP
.RS

.nf
KNOTW \_\_mmask16 \_mm512\_knot(\_\_mmask16 a);

.fi
.RE

.SH FLAGS AFFECTED
.PP
None

.SH SIMD FLOATING\-POINT EXCEPTIONS
.PP
None

.SH OTHER EXCEPTIONS
.PP
See Exceptions Type K20.

.SH SEE ALSO
.PP
x86\-manpages(7) for a list of other x86\-64 man pages.

.SH COLOPHON
.PP
This UNOFFICIAL, mechanically\-separated, non\-verified reference is
provided for convenience, but it may be incomplete or broken in
various obvious or non\-obvious ways. Refer to Intel® 64 and IA\-32
Architectures Software Developer’s Manual for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/ttmo-O/x86-manpages.

.br
MIT licensed by TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
